const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {recoverMessageAddress}=require('viem');
const PORT=process.env.PORT||10000,ROOT=__dirname;
const BASE_RPC_URLS=(process.env.BASE_RPC_URLS||process.env.BASE_RPC_URL||'https://mainnet.base.org,https://base-mainnet.g.alchemy.com/public').split(',').map(x=>x.trim()).filter(Boolean);
const MERCHANT=(process.env.QUANTUM_MERCHANT||'0x13653b6b8bd4b274da565faf6fa894e3418a6d10').toLowerCase();
const USDC='0x833589fcd6edb6e08f4c7c32d4f71b54bda02913'.toLowerCase();
const TRANSFER_TOPIC='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a7f5c5a4d1';
const VERSION='v18';
const products={'Quantum24 Nano':0.24,'Quantum24 Micro':1,'Quantum24 Starter':5,'Quantum24 Basic':10,'Quantum24 Mini':12,'Quantum24 Core':19.24,'Quantum24 Genesis':24,'Quantum24 Plus':49,'Quantum24 Priority':99,'Quantum24 Pro':249,'Quantum24 Business':499,'Quantum24 Enterprise':999,'Quantum24 Scale':2499,'Quantum24 Quantum':9999,'Quantum24 Apex':24000,'Quantum24 Ultra':99999,'Quantum24 Titan':249999,'Quantum24 Infinity':999999};
const aiPoints={'AI Nano':{points:1,usd:.01},'AI Micro':{points:10,usd:.10},'AI Starter':{points:24,usd:.24},'AI Basic':{points:100,usd:1},'AI Pro':{points:1000,usd:10},'AI Quantum':{points:2400,usd:24},'AI Priority':{points:9900,usd:99},'AI Enterprise':{points:99900,usd:999}};
const bankrReferencePricing={'quantum-lite':.10,'quantum-shield':.25,'quantum-timeline':.40,'quantum-premium':1.50,'quantum-batch':2.50,'quantum-contract':5};
const bankrTokenMatrix=['sqt','nqrx','hir','oeql','node','upgrade','rollin','aeth','aiuse','auto','zai','balloon','tree','one','haha','two','caffeine','aiu4','telp','blzet','flaw','wo','emrld','rev'];
const MIN=.01,MAX=10000000,quotes=new Map(),orders=new Map(),usedTx=new Set(),locks=new Set(),challenges=new Map(),sessions=new Map();
const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Content-Security-Policy':"default-src 'self' https:; connect-src 'self' https:; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"};
const send=(r,s,t,b)=>{r.writeHead(s,{'Content-Type':t,...headers});r.end(b)},json=(r,s,o)=>send(r,s,'application/json; charset=utf-8',JSON.stringify(o));
const body=req=>new Promise((ok,bad)=>{let x='';req.on('data',c=>{if(x.length<50000)x+=c});req.on('end',()=>{try{ok(x?JSON.parse(x):{})}catch(e){bad(e)}})});
async function rpc(method,params=[]){let last;for(const url of BASE_RPC_URLS){for(let attempt=0;attempt<2;attempt++){try{const z=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(7000)});if(!z.ok)throw Error('RPC HTTP '+z.status);const j=await z.json();if(j.error)throw Error(j.error.message||'RPC error');return j.result}catch(e){last=e;if(attempt===0)await new Promise(r=>setTimeout(r,250))}}}throw last||Error('Base RPC unavailable')}
const bi=x=>BigInt(x||'0x0');
let ethCache={price:0,at:0};async function ethPrice(){if(ethCache.price>0&&Date.now()-ethCache.at<30000)return ethCache.price;const urls=['https://api.coinbase.com/v2/exchange-rates/ETH?currency=USD','https://api.kraken.com/0/public/Ticker?pair=ETHUSD'];let last;for(const url of urls){try{const z=await fetch(url,{signal:AbortSignal.timeout(5000)});const j=await z.json();const p=Number(j?.data?.rates?.ETH||j?.result?.XETHZUSD?.c?.[0]);if(Number.isFinite(p)&&p>0){ethCache={price:p,at:Date.now()};return p}}catch(e){last=e}}if(ethCache.price>0&&Date.now()-ethCache.at<300000)return ethCache.price;throw last||Error('ETH price unavailable')}
async function live(){const t=Date.now();const block=await rpc('eth_blockNumber');const [eth,balance]=await Promise.allSettled([ethPrice(),rpc('eth_getBalance',[MERCHANT,'latest'])]);return{ok:true,version:VERSION,network:'Base Mainnet',chainId:8453,merchant:MERCHANT,blockNumber:Number(bi(block)),ethUsd:eth.status==='fulfilled'?eth.value:null,merchantEth:balance.status==='fulfilled'?Number(bi(balance.value))/1e18:null,rpcLatencyMs:Date.now()-t,uptimeSeconds:Math.floor(process.uptime()),serverTime:new Date().toISOString(),status:'operational',priceFeedAvailable:eth.status==='fulfilled',balanceAvailable:balance.status==='fulfilled',verifiedPaymentRails:['USDC','ETH'],bankrIntegration:'v18-compatible',failoverRpcCount:BASE_RPC_URLS.length}}
async function quote(product,custom,token='USDC'){let usd=products[product];if(!usd&&Number.isFinite(Number(custom)))usd=Number(custom);if(!usd||usd<MIN||usd>MAX)return null;let price=null,ethWei=null;if(String(token).toUpperCase()==='ETH'){price=await ethPrice();ethWei=BigInt(Math.ceil(usd/price*1e18));}const id='Q24-'+crypto.randomBytes(12).toString('hex');quotes.set(id,{product:product||'Quantum24 Custom',usd,ethWei,created:Date.now()});return{id,product:product||'Quantum24 Custom',amountUsd:usd,ethWei:ethWei?'0x'+ethWei.toString(16):null,ethPriceUsd:price,merchant:MERCHANT,network:'base',token:String(token).toUpperCase()}}
function remember(q,tx,token,from){const k=tx.toLowerCase();if(orders.has(k))return orders.get(k);const o={orderId:'Q24O-'+crypto.randomBytes(8).toString('hex'),intentId:q.id,product:q.product,amountUsd:q.usd,token,from:String(from).toLowerCase(),txHash:k,status:'paid',createdAt:new Date().toISOString()};orders.set(k,o);return o}
async function verify(b){const tx=String(b.txHash||'');if(!/^0x[a-f0-9]{64}$/i.test(tx))return{ok:false,error:'invalid_tx_hash'};const k=tx.toLowerCase();if(locks.has(k))return{ok:true,confirmed:false,status:'verification_in_progress'};if(usedTx.has(k))return{ok:true,confirmed:true,status:'paid',...orders.get(k)};locks.add(k);try{const rec=await rpc('eth_getTransactionReceipt',[tx]);if(!rec)return{ok:true,confirmed:false,status:'pending',txHash:tx};if(rec.status!=='0x1')return{ok:false,confirmed:true,status:'reverted'};const q=quotes.get(String(b.intentId||''));if(!q)return{ok:false,confirmed:true,status:'intent_expired',message:'Intent expired; do not retry the same payment.'};const token=String(b.token||'USDC').toUpperCase(),from=String(b.from||'').toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(from))return{ok:false,confirmed:true,status:'invalid_sender'};if(token==='USDC'){const want=BigInt(Math.round(q.usd*1e6));const match=(rec.logs||[]).some(l=>String(l.address).toLowerCase()===USDC&&String(l.topics?.[0]).toLowerCase()===TRANSFER_TOPIC&&String(l.topics?.[1]||'').toLowerCase().endsWith(from.slice(2))&&String(l.topics?.[2]||'').toLowerCase().endsWith(MERCHANT.slice(2))&&bi(l.data)>=want);if(!match)return{ok:false,confirmed:true,status:'confirmed_wrong_payment'};const o=remember(q,tx,'USDC',from);usedTx.add(k);return{ok:true,confirmed:true,status:'paid',...o,explorer:'https://basescan.org/tx/'+tx}}if(token==='ETH'){const tr=await rpc('eth_getTransactionByHash',[tx]);if(!tr||String(tr.from).toLowerCase()!==from||String(tr.to).toLowerCase()!==MERCHANT)return{ok:false,confirmed:true,status:'confirmed_wrong_recipient'};if(bi(tr.value)!==q.ethWei)return{ok:false,confirmed:true,status:'confirmed_wrong_amount'};const o=remember(q,tx,'ETH',from);usedTx.add(k);return{ok:true,confirmed:true,status:'paid',...o,explorer:'https://basescan.org/tx/'+tx}}return{ok:false,confirmed:true,status:'unsupported_token',supported:['USDC','ETH']}}finally{locks.delete(k)}}
async function txLookup(tx){const [tr,rec]=await Promise.all([rpc('eth_getTransactionByHash',[tx]),rpc('eth_getTransactionReceipt',[tx])]);return tr?{hash:tx,from:tr.from,to:tr.to,value:tr.value,block:tr.blockNumber,status:rec?.status||null,explorer:'https://basescan.org/tx/'+tx}:null}
function catalog(){return{version:VERSION,currency:'USD',network:'Base Mainnet',merchant:MERCHANT,verifiedPaymentRails:['USDC','ETH'],quantumProducts:products,aiPoints,bankrReferencePricing,bankrTokenMatrix,customPriceRange:{minUsd:MIN,maxUsd:MAX},bankr:{app:'quantum24-gains',wallet:MERCHANT,mode:'v18-compatible',tokenEntries:'app-defined; live routes require independent verification'},humanMode:'simple-search-pay-receipt',backendMode:'sales-and-verification',generatedAt:new Date().toISOString()}}
function challenge(){const id=crypto.randomBytes(12).toString('hex'),nonce=crypto.randomBytes(12).toString('hex'),issued=Date.now(),message='Quantum24 v18 owner verification\nMerchant: '+MERCHANT+'\nNonce: '+nonce+'\nIssued: '+new Date(issued).toISOString();challenges.set(id,{message,issued});return{id,message,expiresAt:issued+300000}}
async function ownerVerify(b){const c=challenges.get(String(b.id));if(!c||Date.now()-c.issued>300000)return{ok:false,error:'challenge_expired'};const a=String(b.address||'').toLowerCase();if(a!==MERCHANT)return{ok:false,error:'not_owner_wallet'};const recovered=(await recoverMessageAddress({message:c.message,signature:b.signature})).toLowerCase();if(recovered!==MERCHANT)return{ok:false,error:'invalid_signature'};challenges.delete(String(b.id));const token=crypto.randomBytes(24).toString('hex');sessions.set(token,Date.now());return{ok:true,address:MERCHANT,session:token,expiresAt:Date.now()+3600000}}
function ownerOK(req){const h=String(req.headers.authorization||'');const t=h.startsWith('Bearer ')?h.slice(7):'';const at=sessions.get(t);if(!at||Date.now()-at>3600000){sessions.delete(t);return false}return true}
async function scanPurchases(span=50000){const latest=bi(await rpc('eth_blockNumber')),n=BigInt(Math.min(Math.max(Number(span)||50000,5000),200000)),start=latest>n?latest-n:0n,topicTo='0x'+MERCHANT.slice(2).padStart(64,'0');const rows=[];for(let b=latest;b>=start;b-=5000n){const a=b-4999n>start?b-4999n:start;const logs=await rpc('eth_getLogs',[{address:USDC,topics:[TRANSFER_TOPIC,null,topicTo],fromBlock:'0x'+a.toString(16),toBlock:'0x'+b.toString(16)}]);for(const l of logs)rows.push({token:'USDC',amountUsd:Number(bi(l.data))/1e6,from:'0x'+String(l.topics[1]).slice(-40),txHash:l.transactionHash,block:Number(bi(l.blockNumber)),explorer:'https://basescan.org/tx/'+l.transactionHash});if(rows.length>=500||a===start)break}return{fromBlock:'0x'+start.toString(16),toBlock:'0x'+latest.toString(16),rows:rows.sort((a,b)=>b.block-a.block).slice(0,500)}}
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');const p=u.pathname;
if(p==='/api/health')return json(res,200,{ok:true,service:'quantum24-gains',version:VERSION,network:'base',verifiedRails:['USDC','ETH'],bankrCompatible:true,failover:{rpcEndpoints:BASE_RPC_URLS.length,priceProviders:2,stalePriceWindowSeconds:300},uptimeSeconds:Math.floor(process.uptime())});
if(p==='/api/ready')return json(res,200,{ok:true,ready:true,service:'quantum24-gains',version:VERSION,network:'base',merchant:MERCHANT,failoverRpcCount:BASE_RPC_URLS.length,verifiedPaymentRails:['USDC','ETH']});
if(p==='/api/config')return json(res,200,{ok:true,...catalog()});
if(p==='/api/catalog'||p==='/api/pricing')return json(res,200,{ok:true,...catalog()});
if(p==='/api/live')return json(res,200,await live());
if(p==='/api/live-pricing')return json(res,200,{ok:true,network:'Base Mainnet',chainId:8453,ethUsd:await ethPrice(),usdcUsd:1,productPricing:'fixed USD catalog',updatedAt:new Date().toISOString(),cacheSeconds:30});
if(p==='/api/eth-price')return json(res,200,{ok:true,usd:await ethPrice(),network:'Base Mainnet',updatedAt:new Date().toISOString()});
if(p==='/api/intent'&&req.method==='POST'){const b=await body(req),x=await quote(String(b.product||''),b.customUsd,String(b.token||'USDC'));if(!x)return json(res,400,{ok:false,error:'invalid_product_or_amount'});return json(res,201,{ok:true,status:'ready',...await x,message:'Ready for wallet confirmation. No funds moved.'})}
if(p==='/api/verify'&&req.method==='POST')return json(res,200,await verify(await body(req)));
if(p==='/api/order'&&req.method==='GET'){const tx=String(u.searchParams.get('tx')||'').toLowerCase();return json(res,200,{ok:true,order:orders.get(tx)||null})}
if(p==='/api/receipt'&&req.method==='GET'){const tx=String(u.searchParams.get('tx')||'').toLowerCase();if(!/^0x[a-f0-9]{64}$/.test(tx))return json(res,400,{ok:false,error:'invalid_tx_hash'});return json(res,200,{ok:true,receipt:orders.get(tx)||null,onchain:await txLookup(tx)})}
if(p==='/api/search'&&req.method==='GET'){const q=String(u.searchParams.get('q')||'').trim().toLowerCase();if(/^0x[a-f0-9]{64}$/.test(q)){const tx=await txLookup(q);const order=orders.get(q)||null;return json(res,200,{ok:true,type:'transaction',tx,order,ownership:order?{ownerWallet:order.from,merchantWallet:MERCHANT,paidOnchain:order.status==='paid',chain:'Base Mainnet'}:{onchainObserved:!!tx}});}const results=[...Object.entries(products).filter(([n,v])=>n.toLowerCase().includes(q)||String(v).includes(q)).map(([product,amountUsd])=>({kind:'quantum',product,amountUsd,action:'pay',paymentRail:'USDC_or_ETH'})),...Object.entries(aiPoints).filter(([n,x])=>n.toLowerCase().includes(q)||String(x.points).includes(q)).map(([product,x])=>({kind:'ai',product,amountUsd:x.usd,points:x.points})),...bankrTokenMatrix.filter(x=>x.includes(q)).map(token=>({kind:'bankr-token',token,status:'app-defined; live payment route not independently verified'}))];return json(res,200,{ok:true,type:'quantum_search',query:q,results})}
if(p==='/api/owner/challenge'&&req.method==='POST')return json(res,200,{ok:true,...challenge()});
if(p==='/api/owner/verify'&&req.method==='POST')return json(res,200,await ownerVerify(await body(req)));
if(p==='/api/owner/purchases'&&req.method==='GET'){if(!ownerOK(req))return json(res,401,{ok:false,error:'owner_auth_required'});return json(res,200,{ok:true,owner:MERCHANT,localOrders:[...orders.values()].slice(-500).reverse(),onchain:await scanPurchases(u.searchParams.get('blocks'))})}
if(p==='/download/quantum-catalog.json')return send(res,200,mime['.json'],JSON.stringify(catalog(),null,2));
if(req.method==='GET'){let file=p==='/index.html'||p==='/'?'index.html':path.basename(p);if(!['index.html','manifest.webmanifest','sw.js'].includes(file))return send(res,404,'text/plain; charset=utf-8','Not found');const f=path.join(ROOT,file);return fs.readFile(f,(e,d)=>e?send(res,404,'text/plain; charset=utf-8','Quantum24 file not found'):send(res,200,mime[path.extname(f)]||'application/octet-stream',d))}
return json(res,404,{ok:false,error:'not_found'})}catch(e){console.error(e);return json(res,500,{ok:false,error:'server_error',message:e.message})}}).listen(PORT,'0.0.0.0',()=>console.log('Quantum24 '+VERSION+' listening on '+PORT));
