const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const { recoverMessageAddress }=require('viem');
const PORT=process.env.PORT||10000,ROOT=__dirname,BASE_RPC=process.env.BASE_RPC_URL||'https://mainnet.base.org';
const MERCHANT=(process.env.QUANTUM_MERCHANT||'0x13653b6b8bd4b274da565faf6fa894e3418a6d10').toLowerCase();
const USDC='0x833589fcd6edb6e08f4c7c32d4f71b54bda02913'.toLowerCase();
const TRANSFER_TOPIC='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a7f5c5a4d1';
const products={'Quantum24 Nano':0.24,'Quantum24 Micro':1,'Quantum24 Starter':5,'Quantum24 Basic':10,'Quantum24 Mini':12,'Quantum24 Core':19.24,'Quantum24 Genesis':24,'Quantum24 Plus':49,'Quantum24 Priority':99,'Quantum24 Pro':249,'Quantum24 Business':499,'Quantum24 Enterprise':999,'Quantum24 Scale':2499,'Quantum24 Quantum':9999,'Quantum24 Apex':24000,'Quantum24 Ultra':99999,'Quantum24 Titan':249999,'Quantum24 Infinity':999999};
const MIN_CUSTOM_USD=0.01,MAX_CUSTOM_USD=10000000;
const aiPoints={
  "AI Nano":{points:1,usd:0.01},"AI Micro":{points:10,usd:0.10},"AI Starter":{points:24,usd:0.24},
  "AI Basic":{points:100,usd:1},"AI Pro":{points:1000,usd:10},"AI Quantum":{points:2400,usd:24},
  "AI Priority":{points:9900,usd:99},"AI Enterprise":{points:99900,usd:999}
};
const bankrReferencePricing={
  "quantum-lite":0.10,"quantum-shield":0.25,"quantum-timeline":0.40,
  "quantum-premium":1.50,"quantum-batch":2.50,"quantum-contract":5.00
};
const priceRegistryVersion="2026-10-05";
const quotes=new Map(),challenges=new Map(),sessions=new Map(),orders=new Map(),usedTx=new Set();
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
const send=(r,s,t,b)=>{r.writeHead(s,{'Content-Type':t,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer'});r.end(b)};
const json=(r,s,o)=>send(r,s,'application/json; charset=utf-8',JSON.stringify(o));
function body(q){return new Promise((ok,bad)=>{let x='';q.on('data',c=>{if(x.length<30000)x+=c});q.on('end',()=>{try{ok(x?JSON.parse(x):{})}catch(e){bad(e)}})})}
async function rpc(method,params=[]){const z=await fetch(BASE_RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})});const j=await z.json();if(j.error)throw Error(j.error.message||'Base RPC error');return j.result}
function bi(x){return BigInt(x||'0x0')}
async function ethPrice(){const z=await fetch('https://api.coinbase.com/v2/exchange-rates/ETH?currency=USD');const j=await z.json();const p=Number(j?.data?.rates?.ETH);if(!p||!Number.isFinite(p))throw Error('ETH price unavailable');return p}
async function createIntent(product,customUsd){let usd=products[product];if(!usd&&Number.isFinite(Number(customUsd)))usd=Number(customUsd);if(!usd||usd<MIN_CUSTOM_USD||usd>MAX_CUSTOM_USD)return null;const price=await ethPrice(),ethWei=BigInt(Math.ceil((usd/price)*1e18)),id='Q24-'+crypto.randomBytes(12).toString('hex');quotes.set(id,{product:product||`Quantum24 Custom ${usd.toFixed(2)}`,usd,ethWei,created:Date.now(),status:'ready'});for(const[k,v]of quotes)if(Date.now()-v.created>15*60*1000)quotes.delete(k);return{id,product,amountUsd:usd,ethWei:'0x'+ethWei.toString(16),ethPriceUsd:price,network:'base',merchant:MERCHANT}}
function rememberOrder(q,txHash,token,from,status,extra={}){const key=String(txHash).toLowerCase();const existing=orders.get(key);if(existing)return existing;const row={orderId:'Q24O-'+crypto.randomBytes(10).toString('hex'),intentId:String(q?.id||''),product:q?.product||'Quantum24',amountUsd:q?.usd||0,token:String(token||'').toUpperCase(),from:String(from||'').toLowerCase(),txHash:key,status,createdAt:new Date().toISOString(),...extra};orders.set(key,row);return row}
async function verifyPayment(b){const tx=String(b.txHash||'');if(!/^0x[a-fA-F0-9]{64}$/.test(tx))return{ok:false,error:'invalid_tx_hash'};const existing=orders.get(tx.toLowerCase());if(existing&&existing.status==='paid')return{ok:true,confirmed:true,status:'paid',...existing,explorer:'https://basescan.org/tx/'+tx};const rec=await rpc('eth_getTransactionReceipt',[tx]);if(!rec)return{ok:true,confirmed:false,status:'pending',txHash:tx};if(rec.status!=='0x1')return{ok:false,confirmed:true,status:'reverted'};const q=quotes.get(String(b.intentId||''));if(!q)return{ok:false,confirmed:true,status:'unknown_or_expired_intent'};const token=String(b.token||'USDC').toUpperCase();if(token==='USDC'){const want=BigInt(Math.round(q.usd*1e6)),from=String(b.from||'').replace(/^0x/,'').toLowerCase();const logs=(rec.logs||[]).filter(l=>String(l.address).toLowerCase()===USDC&&String(l.topics?.[0]).toLowerCase()===TRANSFER_TOPIC);const match=logs.some(l=>String(l.topics?.[1]||'').toLowerCase().endsWith(from)&&String(l.topics?.[2]||'').toLowerCase().endsWith(MERCHANT.slice(2))&&bi(l.data)>=want);if(!match)return{ok:false,confirmed:true,status:'confirmed_wrong_payment'};const order=rememberOrder(q,tx,token,from,'paid');usedTx.add(tx.toLowerCase());return{ok:true,confirmed:true,status:'paid',...order,explorer:'https://basescan.org/tx/'+tx}}if(token!=='ETH')return{ok:false,confirmed:true,status:'unsupported_token'};const tr=await rpc('eth_getTransactionByHash',[tx]);if(!tr||String(tr.from||'').toLowerCase()!==String(b.from||'').toLowerCase()||String(tr.to||'').toLowerCase()!==MERCHANT)return{ok:false,confirmed:true,status:'confirmed_wrong_recipient'};if(bi(tr.value)!==q.ethWei)return{ok:false,confirmed:true,status:'confirmed_wrong_amount'};const order=rememberOrder(q,tx,'ETH',tr.from,'paid');usedTx.add(tx.toLowerCase());return{ok:true,confirmed:true,status:'paid',...order,explorer:'https://basescan.org/tx/'+tx}}
function pricingRegistry(){return {
  version:priceRegistryVersion,currency:"USD",network:"base",merchant:MERCHANT,
  quantumProducts:products,aiPoints,bankrReferencePricing,
  custom:{minUsd:MIN_CUSTOM_USD,maxUsd:MAX_CUSTOM_USD,exact:true},
  note:"Current supported Quantum24 pricing registry; historical prices are preserved only when explicitly recorded."
}}
function challenge(){const id=crypto.randomBytes(16).toString('hex'),nonce=crypto.randomBytes(16).toString('hex'),issued=Date.now(),message='Quantum24 owner verification\\nMerchant: '+MERCHANT+'\\nNonce: '+nonce+'\\nIssued: '+new Date(issued).toISOString();challenges.set(id,{message,issued});return{id,message,expiresAt:issued+5*60*1000}}
async function ownerVerify(b){const c=challenges.get(String(b.id||''));if(!c||Date.now()-c.issued>5*60*1000)return{ok:false,error:'challenge_expired'};const address=String(b.address||'').toLowerCase();if(address!==MERCHANT)return{ok:false,error:'not_owner_wallet'};const recovered=(await recoverMessageAddress({message:c.message,signature:b.signature})).toLowerCase();if(recovered!==MERCHANT)return{ok:false,error:'owner_signature_invalid'};challenges.delete(String(b.id));const token=crypto.randomBytes(24).toString('hex');sessions.set(token,{created:Date.now(),address:MERCHANT});return{ok:true,owner:true,address:MERCHANT,session:token,expiresAt:Date.now()+60*60*1000}}
function sessionOK(req){const h=String(req.headers.authorization||'');const token=h.startsWith('Bearer ')?h.slice(7):'';const s=sessions.get(token);if(!s||Date.now()-s.created>60*60*1000){if(token)sessions.delete(token);return false}return s.address===MERCHANT}
async function scanPurchases(fromBlock,toBlock){let end=BigInt(toBlock),start=BigInt(fromBlock),rows=[];const topicTo='0x'+MERCHANT.slice(2).padStart(64,'0');for(let b=end;b>=start;b-=5000n){const a=b-4999n>start?b-4999n:start;const logs=await rpc('eth_getLogs',[{address:USDC,topics:[TRANSFER_TOPIC,null,topicTo],fromBlock:'0x'+a.toString(16),toBlock:'0x'+b.toString(16)}]);for(const l of logs)rows.push({token:'USDC',amountUsd:Number(bi(l.data))/1e6,from:'0x'+String(l.topics[1]).slice(-40),txHash:l.transactionHash,block:Number(bi(l.blockNumber)),explorer:'https://basescan.org/tx/'+l.transactionHash});if(rows.length>=200||a===start)break}return rows.sort((a,b)=>b.block-a.block)}
async function searchChain(qs){const q=String(qs||'').trim().toLowerCase();if(!q)return{type:'catalog',results:[]};if(/^0x[a-f0-9]{64}$/.test(q)){const [tr,rec]=await Promise.all([rpc('eth_getTransactionByHash',[q]),rpc('eth_getTransactionReceipt',[q])]);return{type:'transaction',tx:tr?{hash:q,from:tr.from,to:tr.to,value:tr.value,block:tr.blockNumber,status:rec?.status||null,explorer:'https://basescan.org/tx/'+q}:null}}const quantum=Object.entries(products).filter(([n,p])=>n.toLowerCase().includes(q)||String(p).includes(q)).map(([product,amountUsd])=>({kind:'quantum',product,amountUsd,action:'pay'}));const ai=Object.entries(aiPoints).filter(([n,x])=>n.toLowerCase().includes(q)||String(x.points).includes(q)||String(x.usd).includes(q)).map(([product,x])=>({kind:'ai',product,amountUsd:x.usd,points:x.points,action:'pay'}));const bankr=Object.entries(bankrReferencePricing).filter(([n,p])=>n.toLowerCase().includes(q)||String(p).includes(q)).map(([product,amountUsd])=>({kind:'bankr-x402',product,amountUsd,action:'reference'}));return{type:'quantum_search',query:q,results:[...quantum,...ai,...bankr]}}
http.createServer(async(q,r)=>{try{const u=new URL(q.url,'http://localhost');
if(u.pathname==='/api/health')return json(r,200,{ok:true,service:'quantum24-gains',network:'base',time:new Date().toISOString(),pricePoints:Object.keys(products).length,aiPointPlans:Object.keys(aiPoints).length,onchainSearch:true,quantumSearchAll:true,ownerControls:true});
if(u.pathname==='/api/config')return json(r,200,{ok:true,network:'base',merchant:MERCHANT,usdc:USDC,bankrApiConfigured:Boolean(process.env.BANKR_API_KEY),directOnchainPayments:true,pricePoints:products,aiPoints,bankrReferencePricing,customPriceRange:{min:MIN_CUSTOM_USD,max:MAX_CUSTOM_USD},onchainSearch:true});
if(u.pathname==='/api/eth-price')return json(r,200,{ok:true,usd:await ethPrice()});
if(u.pathname==='/api/intent'&&q.method==='POST'){const ib=await body(q);const x=await createIntent(String(ib.product||''),ib.customUsd);if(!x)return json(r,400,{ok:false,error:'unknown_product'});return json(r,201,{ok:true,status:'ready',...x,message:'Ready for wallet approval; no funds moved.'})}
if(u.pathname==='/api/verify'&&q.method==='POST')return json(r,200,await verifyPayment(await body(q)));
if(u.pathname==='/api/order'&&q.method==='GET'){const tx=String(u.searchParams.get('tx')||'').toLowerCase();if(!/^0x[a-f0-9]{64}$/.test(tx))return json(r,400,{ok:false,error:'invalid_tx_hash'});const row=orders.get(tx);return json(r,200,{ok:true,order:row||null});}
if(u.pathname==='/api/receipt'&&q.method==='GET'){const tx=String(u.searchParams.get('tx')||'').toLowerCase();const row=orders.get(tx);return json(r,200,{ok:true,receipt:row?{...row,explorer:'https://basescan.org/tx/'+tx}:null});}
if(u.pathname==='/api/search'&&q.method==='GET')return json(r,200,{ok:true,...await searchChain(u.searchParams.get('q'))});
if(u.pathname==='/download/quantum-catalog.json'&&q.method==='GET')return send(r,200,'application/json; charset=utf-8',JSON.stringify({name:'Quantum24 Complete Search Catalog',version:priceRegistryVersion,network:'Base',merchant:MERCHANT,quantumProducts:products,aiPoints,bankrReferencePricing,customPriceRange:{min:MIN_CUSTOM_USD,max:MAX_CUSTOM_USD},generatedAt:new Date().toISOString()},null,2));
if(u.pathname==='/api/files'&&q.method==='GET'){const term=String(u.searchParams.get('q')||'').toLowerCase();const allowed=['index.html','manifest.webmanifest','sw.js'];const files=allowed.map(name=>{const f=path.join(ROOT,name);return{file:name,readable:true,download:'/download/'+name,size:fs.existsSync(f)?fs.statSync(f).size:0}}).filter(x=>!term||x.file.toLowerCase().includes(term));return json(r,200,{ok:true,files});}
if(u.pathname.startsWith('/download/')&&q.method==='GET'){const name=path.basename(u.pathname.slice('/download/'.length));if(!['index.html','manifest.webmanifest','sw.js'].includes(name))return json(r,404,{ok:false,error:'file_not_available'});const f=path.join(ROOT,name);return fs.readFile(f,(e,d)=>e?json(r,404,{ok:false,error:'file_not_found'}):send(r,200,mime[path.extname(f)]||'application/octet-stream',d));}
if(u.pathname==='/api/pricing'&&q.method==='GET')return json(r,200,{ok:true,...pricingRegistry()});
if(u.pathname==='/api/performance'&&q.method==='GET')return json(r,200,{ok:true,service:'quantum24-gains',uptimeSeconds:Math.floor(process.uptime()),memory:process.memoryUsage(),activeQuotes:quotes.size,activeOwnerSessions:sessions.size,activeChallenges:challenges.size,orders:orders.size,verifiedPayments:usedTx.size,quantumPriceCount:Object.keys(products).length,aiPlanCount:Object.keys(aiPoints).length,customPriceMin:MIN_CUSTOM_USD,customPriceMax:MAX_CUSTOM_USD});
if(u.pathname==='/api/catalog'&&q.method==='GET')return json(r,200,{ok:true,...pricingRegistry()});
if(u.pathname==='/api/owner/challenge'&&q.method==='POST')return json(r,200,{ok:true,...challenge()});
if(u.pathname==='/api/owner/verify'&&q.method==='POST')return json(r,200,await ownerVerify(await body(q)));
if(u.pathname==='/api/owner/purchases'&&q.method==='GET'){if(!sessionOK(q))return json(r,401,{ok:false,error:'owner_auth_required'});const latest=BigInt(await rpc('eth_blockNumber'));const requested=u.searchParams.get('blocks');const span=BigInt(Math.min(Math.max(Number(requested||50000),5000),200000));return json(r,200,{ok:true,owner:MERCHANT,fromBlock:'0x'+(latest-span).toString(16),toBlock:'0x'+latest.toString(16),purchases:[...orders.values()].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,500),onchainScan:await scanPurchases(latest-span,latest)})}
if(q.method==='GET'){let p=u.pathname;if(p==='/')p='/index.html';const f=path.normalize(path.join(ROOT,p));if(!f.startsWith(ROOT))return send(r,403,'text/plain','Forbidden');return fs.readFile(f,(e,d)=>e?send(r,404,'text/plain','Quantum24 page not found'):send(r,200,mime[path.extname(f)]||'application/octet-stream',d))}
return json(r,404,{ok:false,error:'not_found'});
}catch(e){return json(r,500,{ok:false,error:'server_error',message:e.message})}}).listen(PORT,'0.0.0.0',()=>console.log('Quantum24 listening on '+PORT));