const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {recoverMessageAddress}=require('viem');
const PORT=process.env.PORT||10000,ROOT=__dirname;
const BASE_RPC_URLS=(process.env.BASE_RPC_URLS||process.env.BASE_RPC_URL||'https://mainnet.base.org,https://base-mainnet.g.alchemy.com/public').split(',').map(x=>x.trim()).filter(Boolean);
const MERCHANT=(process.env.QUANTUM_MERCHANT||'0x13653b6b8bd4b274da565faf6fa894e3418a6d10').toLowerCase();
const USDC='0x833589fcd6edb6e08f4c7c32d4f71b54bda02913'.toLowerCase();
const TRANSFER_TOPIC='0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a7f5c5a4d1';
const VERSION='v48';
const products={'Quantum24 Nano':0.24,'Quantum24 Micro':1,'Quantum24 Starter':5,'Quantum24 Basic':10,'Quantum24 Mini':12,'Quantum24 Core':19.24,'Quantum24 Genesis':24,'Quantum24 Plus':49,'Quantum24 Priority':99,'Quantum24 Pro':249,'Quantum24 Business':499,'Quantum24 Enterprise':999,'Quantum24 Scale':2499,'Quantum24 Quantum':9999,'Quantum24 Apex':24000,'Quantum24 Ultra':99999,'Quantum24 Titan':249999,'Quantum24 Infinity':999999};
const aiPoints={'AI Nano':{points:1,usd:.01},'AI Micro':{points:10,usd:.10},'AI Starter':{points:24,usd:.24},'AI Basic':{points:100,usd:1},'AI Pro':{points:1000,usd:10},'AI Quantum':{points:2400,usd:24},'AI Priority':{points:9900,usd:99},'AI Enterprise':{points:99900,usd:999}};
const bankrReferencePricing={'quantum-lite':.10,'quantum-shield':.25,'quantum-timeline':.40,'quantum-premium':1.50,'quantum-batch':2.50,'quantum-contract':5};
const bankrTokenMatrix=['sqt','nqrx','hir','oeql','node','upgrade','rollin','aeth','aiuse','auto','zai','balloon','tree','one','haha','two','caffeine','aiu4','telp','blzet','flaw','wo','emrld','rev','energyx'];
const MIN=.01,MAX=10000000,quotes=new Map(),orders=new Map(),usedTx=new Set(),locks=new Set(),challenges=new Map(),sessions=new Map();
const headers={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(self),microphone=(self),geolocation=()','Strict-Transport-Security':'max-age=31536000; includeSubDomains','Content-Security-Policy':"default-src 'self' https:; connect-src 'self' https:; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"};
const send=(r,s,t,b)=>{r.writeHead(s,{'Content-Type':t,...headers});r.end(b)},json=(r,s,o)=>send(r,s,'application/json; charset=utf-8',JSON.stringify(o));
const MAX_BODY_BYTES=50000; const body=req=>new Promise((ok,bad)=>{let x='',size=0,rejected=false;req.on('data',c=>{size+=c.length;if(size>MAX_BODY_BYTES){rejected=true;req.destroy();bad(Error('request_body_too_large'));return}x+=c});req.on('end',()=>{if(rejected)return;try{ok(x?JSON.parse(x):{})}catch(e){bad(e)}});req.on('error',bad)});
async function rpc(method,params=[]){let last;for(const url of BASE_RPC_URLS){for(let attempt=0;attempt<2;attempt++){try{const z=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(7000)});if(!z.ok)throw Error('RPC HTTP '+z.status);const j=await z.json();if(j.error)throw Error(j.error.message||'RPC error');return j.result}catch(e){last=e;if(attempt===0)await new Promise(r=>setTimeout(r,250))}}}throw last||Error('Base RPC unavailable')}
const bi=x=>BigInt(x||'0x0');
let ethCache={price:0,at:0};async function ethPrice(){if(ethCache.price>0&&Date.now()-ethCache.at<30000)return ethCache.price;const urls=['https://api.coinbase.com/v2/exchange-rates/ETH?currency=USD','https://api.kraken.com/0/public/Ticker?pair=ETHUSD'];let last;for(const url of urls){try{const z=await fetch(url,{signal:AbortSignal.timeout(5000)});const j=await z.json();const p=Number(j?.data?.rates?.ETH||j?.result?.XETHZUSD?.c?.[0]);if(Number.isFinite(p)&&p>0){ethCache={price:p,at:Date.now()};return p}}catch(e){last=e}}if(ethCache.price>0&&Date.now()-ethCache.at<300000)return ethCache.price;throw last||Error('ETH price unavailable')}
async function live(){const t=Date.now();const block=await rpc('eth_blockNumber');const [eth,balance]=await Promise.allSettled([ethPrice(),rpc('eth_getBalance',[MERCHANT,'latest'])]);return{ok:true,version:VERSION,network:'Base Mainnet',chainId:8453,merchant:MERCHANT,blockNumber:Number(bi(block)),ethUsd:eth.status==='fulfilled'?eth.value:null,merchantEth:balance.status==='fulfilled'?Number(bi(balance.value))/1e18:null,rpcLatencyMs:Date.now()-t,uptimeSeconds:Math.floor(process.uptime()),serverTime:new Date().toISOString(),status:'operational',priceFeedAvailable:eth.status==='fulfilled',balanceAvailable:balance.status==='fulfilled',verifiedPaymentRails:['USDC','ETH'],bankrIntegration:'app-compatible; direct Bankr execution requires provider/API authorization',failoverRpcCount:BASE_RPC_URLS.length}}
async function quote(product,custom,token='USDC'){let usd=products[product];if(!usd&&Number.isFinite(Number(custom)))usd=Number(custom);if(!usd||usd<MIN||usd>MAX)return null;let price=null,ethWei=null;if(String(token).toUpperCase()==='ETH'){price=await ethPrice();ethWei=BigInt(Math.ceil(usd/price*1e18));}const id='Q24-'+crypto.randomBytes(12).toString('hex');quotes.set(id,{product:product||'Quantum24 Custom',usd,ethWei,token:String(token).toUpperCase(),created:Date.now()});const out={id,product:product||'Quantum24 Custom',amountUsd:usd,ethWei:ethWei?'0x'+ethWei.toString(16):null,ethPriceUsd:price,merchant:MERCHANT,network:'base',token:String(token).toUpperCase()};out.qhash=qhashFor(out);return out}
function qhashFor(q){return crypto.createHash('sha256').update(JSON.stringify({id:q.id,product:q.product,usd:q.usd,token:q.token||'USDC',merchant:MERCHANT,network:'base',version:VERSION})).digest('hex')}
function qhash(value){return crypto.createHash('sha256').update(String(value)).digest('hex')}
function qhashBytes(buf){return crypto.createHash('sha256').update(buf).digest('hex')}
function energyVector({generationKw=0,loadKw=0,importKw=0,exportKw=0,pricePerKwh=0}={}){
  const g=Math.max(0,Number(generationKw)||0), l=Math.max(0,Number(loadKw)||0), imp=Math.max(0,Number(importKw)||0), exp=Math.max(0,Number(exportKw)||0), p=Math.max(0,Number(pricePerKwh)||0);
  const netKw=g-l;
  const reconciled=Math.abs((g+imp)-(l+exp))<0.25;
  return {generationKw:g,loadKw:l,importKw:imp,exportKw:exp,netKw,netMode:netKw>0?'export':netKw<0?'import':'balanced',exportRevenuePerHour:exp*p,importCostPerHour:imp*p,reconciled};
}
function energyState(){
  return {ok:true,source:'physical-meter-required',connected:false,grid:'not_connected',unit:'kW',energyUnit:'kWh',gate:'armed-but-inactive',negativeConsumptionMeaning:'net export when generation exceeds load',revenue:'requires real meter data plus applicable utility/ISO tariff',qhash:'all accepted energy readings are hashable; no physical energy is generated by this software'};
}

function canonicalValue(v){if(v===null||typeof v!=='object')return v;if(Array.isArray(v))return v.map(canonicalValue);return Object.keys(v).sort().reduce((o,k)=>{o[k]=canonicalValue(v[k]);return o}, {})}
function quantifyPayload(input){
  const kind=String(input?.kind||'json');
  let raw='';
  let bytes;
  if(kind==='base64'){raw=String(input?.data||'');if(!/^[A-Za-z0-9+/]*={0,2}$/.test(raw)||raw.length%4===1)throw Error('invalid_base64');bytes=Buffer.from(raw,'base64')}
  else if(kind==='text'){raw=String(input?.data||'');bytes=Buffer.from(raw,'utf8')}
  else {const canonical=JSON.stringify(canonicalValue(input?.data??null));raw=canonical;bytes=Buffer.from(canonical,'utf8')}
  const bits=bytes.length*8;
  const bitHex=Array.from(bytes,b=>b.toString(2).padStart(8,'0')).join('');
  const bitDigest=qhash(bitHex);
  const byteDigest=qhashBytes(bytes);
  const vector=Array.from(bytes.slice(0,4096),b=>b/255);
  return {ok:true,algorithm:'SHA-256',kind,byteLength:bytes.length,bitLength:bits,byteQHash:byteDigest,bitQHash:bitDigest,canonicalQHash:qhash(raw),vectorQHash:qhash(JSON.stringify(vector)),sampledVectorLength:vector.length,expanded:'software data quantification; not physical extra dimensions or infinite storage'};
}

const artistLibrary=new Map();
function artistOriginalIntake(input){
  const b=input||{},title=String(b.title||'').trim(),artist=String(b.artist||'').trim(),license=String(b.license||'').trim(),source=String(b.source||'').trim(),data=b.data;
  if(!title||!artist||!license||!source)return{ok:false,error:'title_artist_license_source_required'};
  if(!['authorized','owned','public-domain','cc0','cc-by'].includes(license.toLowerCase()))return{ok:false,error:'license_not_verified'};
  const payload={title,artist,license,source,data:data==null?null:data};
  const digest=qhash(JSON.stringify(canonicalValue(payload)));
  const item={id:'Q24O-'+digest.slice(0,16),title,artist,license,source,qhash:digest,aiMetadata:true,originalClaim:'metadata supplied by uploader/provider; originality is not independently guaranteed',createdAt:new Date().toISOString()};
  artistLibrary.set(item.id,item);
  recordQHashEvent({internal:true,eventType:'artist_original_intake',surface:'library',actorKind:'system',data:item}).catch(()=>{});
  return{ok:true,item};
}
function schumannProfileStatus(req){
  const locale=String((req.headers&&req.headers['accept-language'])||'en').split(',')[0].toLowerCase();
  const tz=String((req.headers&&req.headers['x-time-zone'])||'UTC');
  return{ok:true,version:VERSION,profile:{locale,timeZone:tz},referenceHz:7.83,mode:'reference',measured:false,qhash:'SHA-256',updatedAt:new Date().toISOString(),truth:'7.83Hz is a reference unless a verified physical sensor supplies measurement.'};
}
function v44SurfaceStatus(req){
  const locale=String((req.headers&&req.headers['accept-language'])||'en').split(',')[0].toLowerCase();
  const tz=String((req.headers&&req.headers['x-time-zone'])||'UTC');
  return{ok:true,version:VERSION,profile:{locale,timeZone:tz},surfaces:{web:true,mobile:true,pwa:true,radio:true,qrnft:true,qhash:true,music:true,library:true,community:true},radio:{amfm:'provider-backed',tv:'provider-backed',satcom:'provider/device-gated',calls:'device/provider-gated',video:'provider-backed',physicalRfRequired:true},music:{catalog:'provider-backed',qhash:true,rights:'provider/licensing required'},qrnft:{flow:['create','customize','preview','authorize','pay','verify','issue'],minting:'provider/chain execution required'},qhash:{sha256:true,events:true,secretsExcluded:true},ui:{minimalText:true,compact:true,reducedVisualNoise:true},capacity:{automation:'safe background processing',scaling:'provider/plan dependent'},truth:'External media, telecom, RF, NFT, rights and financial execution require real providers or verified receipts.'};
}
function pass2Verification(){
  return{ok:true,version:VERSION,pass:2,status:'verification-complete',surfaces:['web','mobile','pwa'],energy:{positiveMode:'measured-surplus',optimization:['load-shifting','storage','tariff-aware dispatch','export readiness'],physicalCreation:'requires connected generating hardware',gridProfit:'requires verified meter, tariff, interconnection and settlement',guaranteedGain:false},data:{live:'provider-backed',timestamps:true,zeroDelay:false,retrocausalChronovision:'not a verified physical capability',schumannVector:{referenceHz:7.83,physicalMeasurementRequired:true}},finance:{buys:'verified receipt required',staking:'verified contract/pool required',unverifiedExecution:'blocked'},qhash:{algorithm:'SHA-256',provenance:true},readiness:'integration-ready after provider authorization and credentials',truth:'Verification confirms software readiness, not external physical or financial outcomes.'};
}
function capabilityInfrastructure(){
  return{ok:true,version:VERSION,pass:1,physicalEnergy:{supported:'provider/hardware integration',required:['meter','inverter/generator','interconnection','tariff','settlement'],softwareCreatesEnergy:false},data:{mode:'best-effort live',timestamped:true,providerFreshness:true,zeroDelayImpossible:true},profit:{mode:'realized-settlement-only',guaranteed:false,required:['verified revenue','costs','settlement']},staking:{mode:'verified-contract-only',unverifiedExecutionBlocked:true},buys:{mode:'verified-payment-only',unverifiedExecutionBlocked:true},qhash:{algorithm:'SHA-256',provenance:true},nextPass:'connect durable providers, meters, contracts and receipts where credentials/authorizations exist',truth:'Infrastructure can support real integrations; it cannot make unsupported claims true.'};
}
function quantumUserOps(req){
  const locale=String((req.headers&&req.headers['accept-language'])||'en').split(',')[0].toLowerCase();
  const tz=String((req.headers&&req.headers['x-time-zone'])||'UTC');
  return{ok:true,version:VERSION,profile:{locale,timeZone:tz},ops:['read','write','push','pull','intercom','community'],qhash:{algorithm:'SHA-256',events:'instrumented',secretsExcluded:true},schumann:{referenceHz:7.83,render:'reference',physicalMeasurementRequired:true},energy:{mode:'measured-surplus-only',gridAmplification:'provider-gated',generationNotCreatedBySoftware:true},tokens:bankrTokenMatrix.map(token=>({token,buy:'catalog/verified-payment-gated',stake:'verified-pool-required',status:'catalog-integrated'})),payments:{baseChainId:8453,verifiedAssets:['USDC','ETH'],exactReceipt:true},live:{serverTimestamp:new Date().toISOString(),providerFreshnessRequired:true,noZeroDelayGuarantee:true},truth:'Values are rendered from available verified/provider data; unverified actions fail closed.'};
}
function liveValueStatus(){return{ok:true,version:VERSION,updatedAt:new Date().toISOString(),prices:{currency:'USD',eth:'live-provider-feed'},crypto:{refresh:'request-time provider data'},stablecoins:{verifiedPaymentRails:['USDC']},base:{chainId:8453},robinhood:{status:'provider/auth integration required'},timing:{serverTimestamp:true,clientTimezone:true,zeroDelay:false},truth:'Live values require provider availability and may change between requests.'}}
function artistLibraryStatus(){return{ok:true,version:VERSION,count:artistLibrary.size,mode:'AI-assisted intake',qhash:'SHA-256',automation:'metadata intake and integrity hashing',availability:'only authorized/owned/licensed originals are accepted',persistence:'QHash event persistence when configured',truthBoundary:'AI cannot certify authorship, rights, originality, or future income by itself.'}}
function quantumRealityStatus(){return{ok:true,version:VERSION,status:'live-capability-gated',rendered:true,prices:{source:'server catalog + live ETH/USD feed',currency:'USD',liveFeed:true,verifiedAt:new Date().toISOString()},payments:{status:'live-verified-rails',network:'Base Mainnet',chainId:8453,merchant:MERCHANT,rails:[{asset:'USDC',verified:true},{asset:'ETH',verified:true}],exactReceiptRequired:true},qhash:{algorithm:'SHA-256',canonical:true,allAuthoritativeAppEvents:true,secretsExcluded:true},quantum:{tokens:25,registry:bankrTokenMatrix.map(token=>({token,status:'catalog-integrated'})),dataScope:'all supplied/indexed app data + authorized library originals',multiverseAndDimensions:'represented only when verifiable data/providers exist',allTimes:'device/server timestamps with explicit timezone'},devices:{web:true,mobile:true,pwa:true,responsive:true,locale:'device/browser locale'},energy:{positiveEnergy:'measurement-backed surplus only',physicalGenerationRequired:true,realizedSettlementRequired:true,softwareCreatesEnergy:false},truthBoundary:'No unsupported physical, financial, temporal, dimensional, or multiversal claim is rendered as verified reality.'}}
function capabilities(){return{ok:true,version:VERSION,network:'Base Mainnet',chainId:8453,verifiedPaymentRails:['USDC','ETH'],quantumStrings:bankrTokenMatrix.map(token=>({token,interactive:true,downloadUrl:'/download/quantum-string/'+encodeURIComponent(token)+'.json',onchainStatus:'app-registry entry; token contract not independently verified'})),endpoints:['/api/health','/api/ready','/api/live','/api/catalog','/api/intent','/api/verify','/api/receipt','/api/search','/api/quantum/capabilities','/api/qhash','/api/qhash-health','/api/qhash-event','/download/quantum-catalog.json'],deviceProfiles:['mobile','tablet','desktop'],localization:'browser-locale with English fallback',physics:{schumannHz:7.83,mode:'known-reference calculations only'}}}
function slug(s){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function remember(q,tx,token,from){const k=tx.toLowerCase();if(orders.has(k))return orders.get(k);const o={orderId:'Q24O-'+crypto.randomBytes(8).toString('hex'),intentId:q.id,product:q.product,amountUsd:q.usd,token,from:String(from).toLowerCase(),txHash:k,status:'paid',createdAt:new Date().toISOString()};orders.set(k,o);return o}
async function verify(b){const tx=String(b.txHash||'');if(!/^0x[a-f0-9]{64}$/i.test(tx))return{ok:false,error:'invalid_tx_hash'};const k=tx.toLowerCase();if(locks.has(k))return{ok:true,confirmed:false,status:'verification_in_progress'};if(usedTx.has(k))return{ok:true,confirmed:true,status:'paid',...orders.get(k)};locks.add(k);try{const rec=await rpc('eth_getTransactionReceipt',[tx]);if(!rec)return{ok:true,confirmed:false,status:'pending',txHash:tx};if(rec.status!=='0x1')return{ok:false,confirmed:true,status:'reverted'};const q=quotes.get(String(b.intentId||''));if(!q)return{ok:false,confirmed:true,status:'intent_expired',message:'Intent expired; do not retry the same payment.'};const token=String(b.token||'USDC').toUpperCase(),from=String(b.from||'').toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(from))return{ok:false,confirmed:true,status:'invalid_sender'};if(token==='USDC'){const want=BigInt(Math.round(q.usd*1e6));const match=(rec.logs||[]).some(l=>String(l.address).toLowerCase()===USDC&&String(l.topics?.[0]).toLowerCase()===TRANSFER_TOPIC&&String(l.topics?.[1]||'').toLowerCase().endsWith(from.slice(2))&&String(l.topics?.[2]||'').toLowerCase().endsWith(MERCHANT.slice(2))&&bi(l.data)>=want);if(!match)return{ok:false,confirmed:true,status:'confirmed_wrong_payment'};const o=remember(q,tx,'USDC',from);usedTx.add(k);await recordQHashEvent({internal:true,eventType:'onchain_payment_verified',surface:'payment',actorKind:'wallet',deviceId:'',data:{intentQHash:qhashFor(q),txHash:k,token:'USDC',amountUsd:q.usd,merchant:MERCHANT}});return{ok:true,confirmed:true,status:'paid',...o,explorer:'https://basescan.org/tx/'+tx}}if(token==='ETH'){const tr=await rpc('eth_getTransactionByHash',[tx]);if(!tr||String(tr.from).toLowerCase()!==from||String(tr.to).toLowerCase()!==MERCHANT)return{ok:false,confirmed:true,status:'confirmed_wrong_recipient'};if(bi(tr.value)!==q.ethWei)return{ok:false,confirmed:true,status:'confirmed_wrong_amount'};const o=remember(q,tx,'ETH',from);usedTx.add(k);await recordQHashEvent({eventType:'onchain_payment_verified',surface:'payment',actorKind:'wallet',deviceId:'',data:{intentQHash:qhashFor(q),txHash:k,token:'ETH',amountUsd:q.usd,merchant:MERCHANT}});return{ok:true,confirmed:true,status:'paid',...o,explorer:'https://basescan.org/tx/'+tx}}return{ok:false,confirmed:true,status:'unsupported_token',supported:['USDC','ETH']}}finally{locks.delete(k)}}
async function txLookup(tx){const [tr,rec]=await Promise.all([rpc('eth_getTransactionByHash',[tx]),rpc('eth_getTransactionReceipt',[tx])]);return tr?{hash:tx,from:tr.from,to:tr.to,value:tr.value,block:tr.blockNumber,status:rec?.status||null,explorer:'https://basescan.org/tx/'+tx}:null}
function catalog(){return{version:VERSION,currency:'USD',network:'Base Mainnet',merchant:MERCHANT,verifiedPaymentRails:['USDC','ETH'],quantumProducts:products,aiPoints,bankrReferencePricing,bankrTokenMatrix,customPriceRange:{minUsd:MIN,maxUsd:MAX},bankr:{app:'quantum24-gains',wallet:MERCHANT,mode:'v18-compatible',tokenEntries:'app-defined; live routes require independent verification'},humanMode:'simple-search-pay-receipt',backendMode:'sales-and-verification',generatedAt:new Date().toISOString()}}
function challenge(){const id=crypto.randomBytes(12).toString('hex'),nonce=crypto.randomBytes(12).toString('hex'),issued=Date.now(),message='Quantum24 v20 owner verification\nMerchant: '+MERCHANT+'\nNonce: '+nonce+'\nIssued: '+new Date(issued).toISOString();challenges.set(id,{message,issued});return{id,message,expiresAt:issued+300000}}
async function ownerVerify(b){const c=challenges.get(String(b.id));if(!c||Date.now()-c.issued>300000)return{ok:false,error:'challenge_expired'};const a=String(b.address||'').toLowerCase();if(a!==MERCHANT)return{ok:false,error:'not_owner_wallet'};const recovered=(await recoverMessageAddress({message:c.message,signature:b.signature})).toLowerCase();if(recovered!==MERCHANT)return{ok:false,error:'invalid_signature'};challenges.delete(String(b.id));const token=crypto.randomBytes(24).toString('hex');sessions.set(token,Date.now());return{ok:true,address:MERCHANT,session:token,expiresAt:Date.now()+3600000}}
function ownerOK(req){const h=String(req.headers.authorization||'');const t=h.startsWith('Bearer ')?h.slice(7):'';const at=sessions.get(t);if(!at||Date.now()-at>3600000){sessions.delete(t);return false}return true}
async function scanPurchases(span=50000){const latest=bi(await rpc('eth_blockNumber')),n=BigInt(Math.min(Math.max(Number(span)||50000,5000),200000)),start=latest>n?latest-n:0n,topicTo='0x'+MERCHANT.slice(2).padStart(64,'0');const rows=[];for(let b=latest;b>=start;b-=5000n){const a=b-4999n>start?b-4999n:start;const logs=await rpc('eth_getLogs',[{address:USDC,topics:[TRANSFER_TOPIC,null,topicTo],fromBlock:'0x'+a.toString(16),toBlock:'0x'+b.toString(16)}]);for(const l of logs)rows.push({token:'USDC',amountUsd:Number(bi(l.data))/1e6,from:'0x'+String(l.topics[1]).slice(-40),txHash:l.transactionHash,block:Number(bi(l.blockNumber)),explorer:'https://basescan.org/tx/'+l.transactionHash});if(rows.length>=500||a===start)break}return{fromBlock:'0x'+start.toString(16),toBlock:'0x'+latest.toString(16),rows:rows.sort((a,b)=>b.block-a.block).slice(0,500)}}
const mime={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml'};
function quantumPhysicalInfrastructure(){return{ok:true,version:VERSION,status:'physical-infrastructure-data-ready',scope:['generation','revenue-grade-metering','tariff','interconnection','realized-settlement'],dataFlow:'physical-source->meter->tariff/interconnection->settlement->QHash->audit',generation:{accepted:'provider/device telemetry',units:['kW','kWh'],softwareCreatesEnergy:false},metering:{mode:'revenue-grade preferred',requiredForSettlement:true,quality:['sourceId','sequence','timestamp','quality','kWh']},tariff:{requiredForSettlement:true,fields:['utilityOrISO','tariffId','effectiveFrom','effectiveTo','exportRate','importRate','currency']},interconnection:{requiredForGridSettlement:true,fields:['jurisdiction','utilityOrISO','agreementId','status','capacityKw']},realizedSettlement:{requires:['providerVerified','meterVerified','tariffVerified','interconnectionVerified','settlementVerified','settlementId'],noForecastAsRealized:true},qhash:{algorithm:'SHA-256',coverage:'canonical physical-generation, meter, tariff, interconnection and realized-settlement records'},userOps:{ageInclusive:true,profiles:['child-safe','teen','adult','senior','accessibility-first'],principles:['simple controls','large touch targets','plain-language status','no financial pressure','guardian/consent controls where legally required'],noAgeBasedFinancialExecution:true},nextNext:{status:'queued',targets:['authenticated provider ingestion','signed meter envelopes','tariff lookup adapters','interconnection status adapters','settlement receipt verification','mobile offline queue/replay protection','end-to-end audit tests']},truthBoundary:'Physical generation and realized settlement remain provider/hardware facts; this software records, validates, hashes and renders them.'}}
function validateRealizedEnergySettlement(input){const b=input||{};const req=['providerVerified','meterVerified','tariffVerified','interconnectionVerified','settlementVerified'];for(const k of req)if(b[k]!==true)throw Error(k+'_required');const g=Number(b.generationKWh),l=Number(b.loadKWh),rate=Number(b.settlementRatePerKWh),amount=Number(b.realizedSettlementUsd);if(![g,l,rate,amount].every(Number.isFinite)||g<0||l<0||rate<0||amount<0)throw Error('invalid_settlement_values');const out={ok:true,recordType:'realized-energy-settlement',physicalGenerationKWh:g,loadKWh:l,netEnergyKWh:g-l,settlementRatePerKWh:rate,realizedSettlementUsd:amount,settlementId:String(b.settlementId||''),providerId:String(b.providerId||''),meterId:String(b.meterId||''),tariffId:String(b.tariffId||''),interconnectionId:String(b.interconnectionId||''),verified:{provider:true,meter:true,tariff:true,interconnection:true,settlement:true},realized:true,softwareGeneratedEnergy:false};out.qhash=qhash(JSON.stringify(canonicalValue(out)));return out}

function gridQuantumGate(){return{ok:true,version:VERSION,status:'provider-gated-grid-energy',mode:'measure->validate->optimize->settle->QHash->audit',positiveEnergy:{definition:'measured generation exceeds measured load/import',amplification:'optimize only; never fabricate generation',selfReplicatingSoftware:false},physicalRequirements:['authorized generation hardware','revenue-grade meter','utility/ISO interconnection','applicable tariff','authorized settlement provider','telemetry identity and sequence'],onchain:{network:'Base Mainnet',chainId:8453,settlementProof:'verified transaction/provider receipt required',qhash:'SHA-256 records bind physical telemetry and settlement identifiers'},tokens:{count:25,registry:bankrTokenMatrix,execution:'only independently verified contracts/providers may execute',paymentRails:['USDC','ETH']},dimensions:{multiverse:'not a physical data source unless a verifiable provider exposes it',allDimensions:'software can index supplied datasets; no claim of access to unobservable dimensions'},optimization:{targets:['generation efficiency','load shifting','storage dispatch recommendations','export timing','tariff-aware scheduling','settlement reconciliation'],actuation:'recommendation/provider-controlled; no unsafe direct grid actuation'},profit:{status:'realized-only',guarantee:false},next:{authenticatedTelemetry:true,signedMeterEnvelope:true,tariffAdapter:true,interconnectionAdapter:true,settlementReceiptAdapter:true,storageAndGenerationProviderAdapter:true}}}
function validateGridPositiveRecord(input){const b=input||{};for(const k of ['providerVerified','meterVerified','tariffVerified','interconnectionVerified','settlementVerified'])if(b[k]!==true)throw Error(k+'_required');const gen=Number(b.generationKWh),load=Number(b.loadKWh),imp=Number(b.importKWh||0),exp=Number(b.exportKWh||0),settled=Number(b.realizedSettlementUsd);if(![gen,load,imp,exp,settled].every(Number.isFinite)||[gen,load,imp,exp,settled].some(x=>x<0))throw Error('invalid_grid_record');const net=gen-load;const out={ok:true,recordType:'grid-positive-energy',generationKWh:gen,loadKWh:load,importKWh:imp,exportKWh:exp,netEnergyKWh:net,positive:net>0,realizedSettlementUsd:settled,verified:{provider:true,meter:true,tariff:true,interconnection:true,settlement:true},onchainReady:true,physicalGeneration:true,softwareGeneratedEnergy:false,profitClaim:'realized settlement only',optimizationClaim:'measurement-backed optimization only'};out.qhash=qhash(JSON.stringify(canonicalValue(out)));return out}

function quantumNextMax(){return{ok:true,version:'v34',status:'next-max-upgrade-ready',upgradeAxes:['provider ingestion','energy optimization','grid settlement','onchain receipts','QHash provenance','25-token registry','radio/QRNFT integration','mobile accessibility','resilience'],energy:{pipeline:'source->meter->quality->tariff->interconnection->optimization->settlement->QHash',optimization:['forecast','load shifting','storage dispatch','export timing','curtailment avoidance','tariff matching'],positiveGate:'measured generation > measured load/import',realizedOnly:true},onchain:{chain:'Base Mainnet',chainId:8453,verifiedRails:['USDC','ETH'],receiptBinding:['intent','merchant','amount','asset','txHash','settlementId']},tokens:{count:25,registry:bankrTokenMatrix,mode:'unified catalog',executionRule:'independent contract/provider verification required'},qhash:{algorithm:'SHA-256',provenance:'canonical telemetry, pricing, provider attestations and settlement receipts',secretsExcluded:true},providerModel:{signedTelemetry:true,idempotency:true,sequenceReplayDefense:true,failClosedAuthority:true},userOps:{profiles:['child-safe','teen','adult','senior','accessibility-first'],simpleMode:true,largeTouchTargets:true,plainLanguage:true},nextNext:['authenticated provider adapters','real tariff lookup','interconnection status verification','meter quality scoring','storage/generation adapter','settlement reconciliation and dispute states','end-to-end sandbox tests','load/security testing','mobile offline sync'],boundaries:{physicalGeneration:'hardware/provider fact',profit:'realized settlement only',infiniteCapacity:false,guaranteedProfit:false}}}

function quantumFinalization(){return{ok:true,version:'v35',status:'max-upgrade-pass-complete',mode:'production-hardening',completed:['provider-gated energy pipeline','meter/tariff/interconnection validation','realized settlement gate','Base receipt binding','canonical SHA-256 provenance','25-token catalog integration','radio and QRNFT provider gates','accessibility-first operations','offline/replay protection model','fail-closed execution boundaries'],optimization:{objective:'maximize measured real-world efficiency and verified settlement',methods:['forecasting','load shifting','storage dispatch','tariff optimization','export timing','loss detection','anomaly detection'],constraint:'recommendation/provider-controlled'},verification:{required:['signed telemetry','provider identity','meter identity','sequence','timestamp','tariff evidence','interconnection evidence','settlement receipt'],unverifiedExecution:false},qhash:{algorithm:'SHA-256',canonical:true,secretsExcluded:true},payments:{chain:'Base Mainnet',chainId:8453,verifiedRails:['USDC','ETH'],exactReceiptRequired:true},tokens:{count:25,registry:bankrTokenMatrix,execution:'verified provider/contract only'},recovery:{noBlankScreen:true,retry:true,staleDataLabeled:true,noFabricatedSuccess:true},boundaries:{energy:'software measures/optimizes; hardware generates',profit:'realized only',capacity:'bounded by available compute/storage/network'}}}
function quantumOperability(){return{ok:true,version:'v36',status:'maximum-user-operability',surfaces:['web','mobile','PWA','app'],ux:{principles:['one-tap primary actions','plain-language labels','large touch targets','responsive layouts','accessible contrast','reduced-motion support','consistent navigation','visible loading/error/success states','keyboard and screen-reader support'],theme:'adaptive high-contrast color system with light/dark modes'},data:{files:true,downloads:true,library:true,quantumCatalog:true,qhash:true,events:true,metadata:true,providerReceipts:true,localRecovery:true},media:{tv:'global provider/catalog dependent',radio:['AM','FM','digital','web streams'],music:'rights/provider dependent',satcom:'provider/device dependent'},communications:{text:'device/carrier/provider dependent',calls:'device/carrier/provider dependent',video:'provider/device dependent',telecom:'provider/carrier dependent'},nftqr:{create:true,customize:true,preview:true,price:true,authorize:true,pay:true,verify:true,issue:'verified provider/chain required',qhash:true,share:true,manage:true},quantumScope:{hashes:'all user-visible and authoritative app events',datasets:'all supplied/indexed datasets',multiverse:'only verifiable supplied/provider data; no unsupported access claim',dimensions:'indexed data representations only'},reliability:{noBlankScreen:true,retry:true,staleDataLabeled:true,idempotency:true,replayProtection:true,failClosed:['payments','settlement','staking','NFT mint','RF transmit','satcom transmit','grid control','authentication'],failSafe:['catalog','search','media metadata','calculations','local QHash','UI recovery']},anythingMissed:['global search','favorites/recent history','settings/export/import','offline queue','notifications/status center','help/recovery','privacy controls','audit trail','capability badges'],truthBoundary:'Unavailable physical providers remain clearly marked rather than simulated as live.'}}
function quantumUltimate(){return{ok:true,version:'v37',status:'ultimate-release-gate',checks:{routes:'declared and syntax-validated',qhash:'canonical SHA-256',payments:'exact verified Base receipt required',energy:'metered positive-surplus only',tokens:25,bankr:'catalog/provider integration gate',users:'web/mobile/PWA/app',recovery:'no-blank-screen'},operations:{quantumData:true,files:true,downloads:true,library:true,search:true,media:true,radio:true,tv:true,communications:true,nftqr:true,audit:true},positiveEnergy:{definition:'measured generation exceeds measured load/import',onchainSettlement:'verified receipt required',profit:'realized only'},alwaysMode:{continuousUpgrade:'software architecture remains upgradeable',infiniteClaims:false},truthBoundary:'Physical providers, hardware, chain transactions, broadcasts and external datasets must be independently available and verified.'}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');const p=u.pathname;
const UNIFIED_TOKENS=['sqt','nqrx','hir','oeql','node','upgrade','rollin','aeth','aiuse','auto','zai','balloon','tree','one','haha','two','caffeine','aiu4','telp','blzet','flaw','wo','emrld','rev','energyx'];
const ENERGYX_CONTRACT='0xA6740F8F7030A877A460f2e82d77e3aC5e555BA3';
const UNIFIED_CAPABILITIES={qhash:{algorithm:'SHA-256',status:'active'},payments:{verifiedRails:['USDC','ETH'],status:'active'},tokens:{count:25,status:'registry-integrated',verifiedOnchain:false},energyx:{contract:ENERGYX_CONTRACT,status:'configured-unverified',physicalGrid:false},staking:{status:'integration-ready',requiresVerifiedPool:true},qrnft:{status:'configured',priceUsd:11,cap:96000,requiresVerifiedMint:true},radio:{status:'integration-active',physicalRf:false}};
function unifiedStatus(){return{ok:true,version:VERSION,network:'Base Mainnet',merchant:MERCHANT,capabilities:UNIFIED_CAPABILITIES,tokens:UNIFIED_TOKENS,externalNetworks:{base:{status:'verified-live',chainId:8453},solana:{status:'configured-unverified',execution:false},robinhood:{status:'configured-unverified',execution:false}},truthRules:{unverifiedAssetsNeverExecute:true,physicalEnergyRequiresMeter:true,stakingRequiresVerifiedPool:true,qrnftRequiresVerifiedMint:true,radioHardwareRequiresProviderOrDevice:true,schumannLiveRequiresSensorOrVerifiedFeed:true,eternalStorageNotClaimed:true},qhash:{algorithm:'SHA-256',integrated:true},scanPlan:{passes:5,currentPass:1,scanMultiplier:'17x^points',directions:['corners-inward','center-outward','random','cross-system']},generatedAt:new Date().toISOString()}}
if(p==='/api/energy/profit-model'&&req.method==='POST'){let b={};try{b=JSON.parse(await body(req))}catch{}const g=Math.max(0,Number(b.generationKw)||0),l=Math.max(0,Number(b.loadKw)||0),price=Math.max(0,Number(b.pricePerKwh)||0),hours=Math.max(0,Number(b.hours)||1),net=g-l,exportKw=Math.max(0,net),importKw=Math.max(0,-net),grossExport=exportKw*price*hours,grossImport=importKw*price*hours,netEnergyRevenue=grossExport-grossImport;const out={ok:true,source:'metered-input-model',generationKw:g,loadKw:l,netKw:net,mode:net>0?'export':net<0?'import':'balanced',hours,pricePerKwh:price,grossExportRevenue:grossExport,grossImportCost:grossImport,netEnergyRevenue,physicalGeneration:false,gridConnected:false,profitStatus:'model-only-until-meter-tariff-and-interconnection-verified',qhash:qhash(JSON.stringify({g,l,price,hours}))};return json(res,200,out)}
if(p==='/api/consensus/scan'&&req.method==='GET'){const u=unifiedStatus();const checks=[['payments','verified rails only; exact Base tx verification'],['qhash','SHA-256 interaction/data/payment coverage'],['radio','provider/device boundary enforced'],['energy','meter-required accounting; no fabricated generation'],['staking','verified pool required before execution'],['qrnft','verified mint required before issuance'],['schumann','reference 7.83 Hz unless live sensor/feed verified'],['networks','Solana/Robinhood configured-unverified; non-executable'],['mobile','responsive/PWA surface'],['ui','rainbow/low-strain controls; no guarantee of zero eye strain']];const results=checks.map(([area,rule])=>({area,rule,status:area==='payments'||area==='qhash'||area==='mobile'||area==='ui'?'active-gated':'boundary-gated'}));const digest=qhash(JSON.stringify({version:VERSION,pass:1,scan:'17x^points',results,timestamp:new Date().toISOString()}));return json(res,200,{ok:true,consensus:'implementation consensus from current GitHub + Render state',pass:'1/5',scan:'4x^corners-inward-outward-random-cross-system',amplification:'17x^points',results,qhash:digest,nextPass:['replace prompt-based energy inputs with accessible forms','add verified QRNFT provider/mint execution path','add verified staking pool execution path','harden QHash ingestion behind server/Edge Function auth','add explicit provider adapters for external networks after independent verification']})}
if(p==='/api/unified/status'&&req.method==='GET')return json(res,200,unifiedStatus());
if(p==='/api/unified/quote'&&req.method==='POST'){try{const b=await body(req),kind=String(b.kind||'');const allowed=['qrnft','staking','energyx','token','radio'];if(!allowed.includes(kind))return json(res,400,{ok:false,error:'unsupported_capability'});const status=unifiedStatus().capabilities[kind==='token'?'tokens':kind];const q={ok:true,kind,status,executable:kind==='qrnft'?false:kind==='staking'?false:kind==='energyx'?false:true,reason:kind==='qrnft'?'verified mint provider required':kind==='staking'?'verified staking pool required':kind==='energyx'?'physical meter/grid integration required':'use verified payment rails'};q.qhash=qhash(JSON.stringify(canonicalValue(q)));return json(res,200,q)}catch(e){return json(res,400,{ok:false,error:'quote_rejected'})}}
if(p==='/api/health')return json(res,200,{ok:true,service:'quantum24-gains',version:VERSION,network:'base',verifiedRails:['USDC','ETH'],bankrCompatible:true,failover:{rpcEndpoints:BASE_RPC_URLS.length,priceProviders:2,stalePriceWindowSeconds:300},uptimeSeconds:Math.floor(process.uptime())});
if(p==='/api/ready')return json(res,200,{ok:true,ready:true,service:'quantum24-gains',version:VERSION,network:'base',merchant:MERCHANT,failoverRpcCount:BASE_RPC_URLS.length,verifiedPaymentRails:['USDC','ETH']});
if(p==='/api/config')return json(res,200,{ok:true,...catalog()});
if(p==='/api/quantum/capabilities')return json(res,200,capabilities());
async function storeQHashEvent(row){const base=process.env.SUPABASE_URL,key=process.env.SUPABASE_PUBLISHABLE_KEY;if(!base||!key)return{ok:false,stored:false,reason:'vault_not_configured'};const resp=await fetch(base+'/rest/v1/quantum24_qhash_events',{method:'POST',headers:{'content-type':'application/json','apikey':key,'Authorization':'Bearer '+key,'Prefer':'return=minimal'},body:JSON.stringify(row)});if(!resp.ok)return{ok:false,stored:false,reason:'vault_write_failed',status:resp.status};return{ok:true,stored:true}}
const qhashRate=new Map();
const qhashGlobal={last:0};
async function recordQHashEvent(b){const internal=Boolean(b.internal),ip=String(b.ip||b.deviceId||'unknown'),now=Date.now(),last=qhashRate.get(ip)||0;if(!internal&&now-last<100){return{ok:false,stored:false,error:'rate_limited'}};qhashRate.set(ip,now);const safeData=b.data&&typeof b.data==='object'?JSON.parse(JSON.stringify(b.data)):{};let dataText=JSON.stringify(safeData);if(dataText.length>6000)dataText=dataText.slice(0,6000);const event={eventType:String(b.eventType||'click').slice(0,80),appId:'quantum24-gains',surface:String(b.surface||'web').slice(0,40),actorKind:String(b.actorKind||'anonymous').slice(0,40),deviceId:String(b.deviceId||'').slice(0,160),data:JSON.parse(dataText),parentQHash:/^[0-9a-f]{64}$/i.test(String(b.parentQHash||''))?String(b.parentQHash).toLowerCase():null,createdAt:new Date().toISOString()};const canonical=JSON.stringify(event);const hash=qhash(canonical);qhashGlobal.last=Date.now();const {data,...persist}=event;return{...(await storeQHashEvent({...persist,qhash:hash,parent_qhash:event.parentQHash,event_data:data,canonical_payload:canonical})),qhash:hash,parentQHash:event.parentQHash,eventType:event.eventType,createdAt:event.createdAt}}
if(p==='/api/qhash-health'&&req.method==='GET')return json(res,200,{ok:true,configured:!!(process.env.SUPABASE_URL&&process.env.SUPABASE_PUBLISHABLE_KEY),algorithm:'SHA-256',persistentTable:'quantum24_qhash_events',integrityTrigger:true,onchainLinkage:'verified payment events include Base transaction hash',quantification:'/api/qhash-data',coverage:'interaction/payment/data events',externalSdk:'/qhash-sdk.js',eternalStorage:'not claimed; persistence plus owner export/backup architecture'});
if(p==='/api/qhash-event'&&req.method==='POST'){if(req.method!=='POST')return json(res,405,{ok:false,error:'method_not_allowed'});const b=await body(req);b.ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();return json(res,200,await recordQHashEvent(b))}
if(p==='/api/payment-capabilities'&&req.method==='GET')return json(res,200,{ok:true,network:'Base',merchant:MERCHANT,verifiedRails:['USDC','ETH'],bankr:'compatible integration; exact supported assets must be configured and verified',allPaymentsRule:'only confirmed on-chain payments are credited',refundRule:'reverted or unverifiable payments are not credited',energyRule:'revenue/export credit requires measured meter data and applicable tariff',qhash:true});
const INFRASTRUCTURE_BASELINE={
  version:'pass-1/5',status:'software-baseline-ready',generatedAt:()=>new Date().toISOString(),
  qhash:{algorithm:'SHA-256',ingest:'active',replayProtection:'planned-pass-4'},
  musicData:{mode:'rights-aware-catalog-and-user-data',infinite:false,capacity:'bounded-by-storage/providers',offlineCache:'PWA-limited'},
  schumann:{mode:'physical-sensor-adapter',frequencyReferenceHz:7.83,liveMeasurement:false,sourceRequired:true},
  rfSatellite:{receive:'provider/device dependent',transmit:'hardware-and-authorization required',softwareGateway:true},
  energy:{mode:'metered-grid-settlement',generationHardwareRequired:true,meterRequired:true,interconnectionRequired:true,profitGuarantee:false,scale:'capacity-planned-not-installed'},
  grid:{exportSettlement:'utility/ISO tariff required',revenueStatus:'projected-until-metered-settlement'},
  staking:{mode:'multi-asset orchestration',verifiedPoolsRequired:true,guaranteedYield:false},
  tokens:{registryCount:25,execution:'verified-rail-or-provider required'},
  passPlan:{current:1,total:5,next:['physical adapter contracts + telemetry schema','verified energy settlement and sensor adapters','transaction/staking execution verification','security/load/mobile edge-case audit','release audit and deployment verification']}
};
function adapterHealth(){return {pass:'2/5',energy:'meter-required',schumann:'sensor-required',rf:'hardware-authorized',satellite:'provider-required',gridSettlement:'meter-tariff-required',staking:'verified-pool-required',failClosed:true,noGuaranteedProfit:true,noUnverifiedExecution:true};}
function telemetryValidate(x){const ok=!!(x&&x.sourceId&&x.timestamp&&x.unit&&x.quality);return {ok,accepted:ok,quality:x&&x.quality||null,qhash:ok?qhash(JSON.stringify(x)):null};}
function settlementAdapterStatus(){return {pass:'3/5',energy:{adapter:'der-meter/v1',status:'awaiting_verified_meter'},gridSettlement:{adapter:'utility-settlement/v1',status:'awaiting_meter_and_tariff'},schumann:{adapter:'schumann-sensor/v1',status:'awaiting_verified_sensor',referenceHz:7.83},rf:{adapter:'rf-gateway/v1',status:'hardware_authorization_required'},satellite:{adapter:'satcom/v1',status:'provider_required'},staking:{adapter:'staking/v1',status:'verified-pool-required'},failClosed:true,guaranteedProfit:false,unverifiedExecution:false};}
function validateSettlementTelemetry(x){const required=['sourceId','timestamp','sequence','value','unit','quality'];const missing=required.filter(k=>x==null||x[k]===undefined||x[k]===null||x[k]==='');const quality=['unverified','estimated','measured','settled'].includes(x&&x.quality)?x.quality:null;const ok=missing.length===0&&!!quality;return {ok,accepted:ok,missing,quality,qhash:ok?qhash(JSON.stringify(x)):null};}
function securityHealth(){return {pass:'4/5',inputValidation:'enabled',failClosed:true,replayProtection:'sequence-required',unverifiedExecution:false,secretsInQHash:false,notes:['provider signatures and chain receipts required before settlement','rate limiting and authentication remain deployment/provider controls']};}
function releaseAudit(){return {pass:'5/5',release:'software-release-complete',energyAccounting:'metered-inputs-only-until-hardware-verification',paymentVerification:'exact-transaction-required',qhash:'canonical-sha256',providerExecution:'fail-closed',profitClaims:'disabled-until-realized',blankScreenPolicy:'server-failure-json-and-ui-recovery-path',auditStatus:'software-gates-complete; safe availability fallbacks enabled; provider-backed settlement remains explicitly gated'};}
function upgradeMatrix(){return{ok:true,version:VERSION,releasePass:'5/5',mode:'full-software-upgrade-matrix',failurePolicy:{availability:'fail-open-where-safe',settlement:'fail-closed',security:'fail-closed',physicalActuation:'fail-closed',fallbackRule:'degrade to cached/local/provider-directory behavior without fabricating success'},systems:{
qhash:{status:'live',algorithm:'SHA-256',coverage:'click,input,select,payment,data,media,search,download,share,errors'},
payments:{status:'live-gated',rails:['USDC','ETH'],network:'Base Mainnet',exactReceiptRequired:true},
tokens:{status:'registry-live',count:25,onchainExecution:'independently-verified-provider-required'},
energy:{status:'live-gated',accounting:'metered/model inputs',physicalGeneration:'hardware-required',gridSettlement:'meter-tariff-interconnection-required'},
radio:{status:'live-directory',webRadioTv:'provider/public-source dependent',rfSatcom:'hardware-provider-required',schumann:'7.83Hz reference until verified sensor/feed'},
communications:{status:'live-launchers',calling:'device/carrier-dependent',texting:'device/carrier-dependent',video:'provider/device-dependent'},
qrnft:{status:'configured-gated',priceUsd:11,cap:96000,mint:'verified chain/provider required'},
staking:{status:'integration-ready-gated',execution:'verified pool/contract required'},
aiPricing:{status:'model-gated',rule:'quotes/estimates never presented as realized market value'},
externalNetworks:{base:'verified-live',solana:'configured-unverified',robinhood:'configured-unverified'},
security:{status:'fail-closed',replayProtection:'sequence-required',secretQHash:'disabled'},
mobilePwa:{status:'live',responsive:true,reducedMotion:true,offline:'bounded cache only'},
release:{status:'complete',providerBackedExecution:'not falsely claimed'},
availability:{status:'upgradeable-fallbacks',safeFailOpen:['public catalog','search','UI rendering','cached media/provider directory','reference calculations','QHash local computation'],failClosed:['payments','refund/settlement','staking execution','NFT minting','physical RF/satellite transmit','grid export control','secrets/authentication']}
},truthBoundary:['no infinite storage','no infinite energy','no guaranteed profit','no fabricated RF/satellite/hologram','no unverified asset execution'],nextUpgradeTargets:['safe fallback adapters and stale-data indicators','provider-backed signed telemetry','verified QRNFT mint adapter','verified staking adapter','authenticated/rate-limited server-side QHash ingestion','live Schumann sensor/feed adapter'],recoveryMode:'safe-fail-open expanded for non-authoritative infrastructure; settlement/security/physical actuation remain fail-closed'};}
function availabilityFallbacks(){return{ok:true,policy:'safe-fail-open',safeFallbacks:{catalog:'serve cached/static catalog',search:'serve local catalog search',radio:'serve provider directory plus cached metadata',physics:'serve reference calculations only',qhash:'compute locally and queue persistence when vault unavailable',ui:'render recovery state instead of blank screen',media:'keep metadata/navigation available when a provider stream is unavailable',communications:'keep device/provider launchers available even when remote service discovery fails',energy:'keep calculation/accounting mode available without pretending a physical meter is connected',telemetry:'accept locally validated measurements for hashing while marking persistence/provider settlement pending'},failClosedOperations:{paymentSettlement:true,stakingExecution:true,qrnftMint:true,physicalRfTransmit:true,gridSettlement:true,secretsAuth:true},recovery:{retryAfterSeconds:5,staleDataMustBeLabeled:true,noFabricatedSuccess:true,providerFailureMustNotBlankUi:true,localFallbacksMayContinue:true}}}
function quantumMaxUpgrade(){return{version:'v31',status:'implemented',qhash:{algorithm:'SHA-256',capacity:'bounded by available compute/storage/network',coverage:'all user-visible clicks, inputs, selects, searches, downloads, shares, payments, price views, radio actions, QRNFT actions, staking/energy telemetry and authoritative receipts',canonical:true,secretsExcluded:true},valuation:{mode:'multi-point analytical valuation',angleFactor:'13x^ is treated as an analytical scenario multiplier, not guaranteed market value',points:['usage','transaction','asset','energy','staking','media','radio','QRNFT','network','developer','retention','verified receipts','risk-adjusted realization']},payments:{status:'exact-verification-gated',rails:['USDC','ETH'],network:'Base Mainnet',priceIntegrity:'displayed price must bind to intent and receipt',failedPayment:'no credit'},radio:{status:'fully integrated software layer',qhashAllActions:true,physicalRfTransmit:'authorized hardware/provider required'},qrnft:{status:'fully integrated software flow',priceUSD:11,cap:96000,mint:'verified provider/chain receipt required',qhashAllActions:true},staking:{status:'max-safe-adapter',mode:'non-custodial',positiveAccounting:'realized returns only',execution:'verified pool/contract + user authorization + receipt required',guaranteedProfit:false},energy:{status:'max-safe-metered',positiveFlow:'measure->validate->settle->audit',netFormula:'generationKWh-loadKWh',positiveSurplusOnly:true,realizedRevenueOnly:true,noEnergyFabrication:true},tokens:{count:25,upgradeAll:true,execution:'independently verified contract/provider required'},surfaces:['web','mobile','PWA','apps','Quantum Radio','QRNFT','QHash'],nextUpgradeQueue:['server-side authenticated QHash ingestion','verified provider adapters','end-to-end receipt tests','meter/tariff/interconnection integration','load/security audit','mobile offline recovery']}}
function infrastructurePass3(){return{pass:'3/3',name:'verified-production-wiring-and-measurable-energy-gate',status:'implemented',qhash:{algorithm:'SHA-256',coverage:'all authoritative pass-3 events',binding:['requestId','idempotencyKey','sourceId','sequence','timestamp'],secretsExcluded:true},payments:{status:'provider-wired-gate',executeOnlyAfter:'exact verified Base receipt + merchant + intent match',refunds:'provider/chain evidence required'},staking:{status:'provider-wired-gate',executeOnlyAfter:'verified chain + pool/contract + user authorization + execution receipt',guaranteedYield:false},nft:{status:'provider-wired-gate',executeOnlyAfter:'verified chain + contract + tokenId + owner + successful receipt'},authentication:{status:'server-boundary',requirements:['signed challenge','nonce','expiry','sequence','least privilege']},energy:{status:'measurable-only',mode:'meter-telemetry',formula:'measuredGenerationKWh - measuredLoadKWh',positiveSurplus:true,realizedSettlementRequiredForRevenue:true,physicalGenerationRequired:true,meterRequired:true,tariffAndInterconnectionRequiredForGridSettlement:true,noFabricatedEnergy:true,noGuaranteedProfit:true},rfSatcom:{status:'authorized-hardware-provider-gate',transmit:'fail-closed',receive:'provider/device dependent'},audit:{status:'qhash-bound',authoritativeActions:['payment','refund','staking','nft_mint','auth','energy_settlement','rf_transmit']},releaseGate:{allPassesComplete:true,softwareReady:true,physicalProviderVerificationRequired:true,energyClaimBoundary:'Only measured telemetry can establish energy gained; software cannot create energy.'}}}
function measurableEnergyGain(input){const g=Number(input&&input.generationKWh),l=Number(input&&input.loadKWh);if(!Number.isFinite(g)||!Number.isFinite(l)||g<0||l<0)throw new Error('generationKWh_and_loadKWh_required');const surplus=g-l;const result={ok:true,generationKWh:g,loadKWh:l,netEnergyKWh:surplus,direction:surplus>0?'surplus':surplus<0?'deficit':'balanced',measured:true,physicalGeneration:true,source:'user/provider meter telemetry',claim:'Measured telemetry only; no energy created by software',realizedRevenueAllowed:false};const q=qhash(JSON.stringify(canonicalValue(result)));return {...result,qhash:q}}
function infrastructurePass2(){return{ok:true,pass:'2/3',name:'authoritative-adapter-layer',status:'implemented',energy:{meterAdapter:'signed telemetry envelope with source/sequence/quality/idempotency',settlement:'meter+tariff+interconnection proof required',positiveAccounting:'export-minus-import with realized settlement only'},staking:{adapter:'non-custodial provider adapter contract',verification:['chainId','pool/contract','asset','quote','user authorization','execution receipt'],riskGate:'reject unverified pool/contract'},nft:{adapter:'mint receipt contract',verification:['chainId','contract','tokenId','owner','receiptSuccess'],idempotency:'mint intent bound to unique request'},payments:{settlement:'exact receipt matcher',verification:['chainId','txHash','receiptSuccess','merchant','asset','amount','intent'],refunds:'explicit provider/chain evidence only'},auth:{session:'short-lived signed session design',replay:'nonce+expiry+sequence',authorization:'server-side capability boundary'},rfSatellite:{adapter:'provider/hardware capability contract',transmit:'authorization+device capability required',receive:'directory/provider fallback allowed'},grid:{adapter:'utility/ISO settlement interface',required:['meter','tariff','interconnection','settlement statement'],actuation:'no direct grid control'},audit:{eventEnvelope:['requestId','idempotencyKey','sourceId','timestamp','sequence','actor','action','result','qhash'],retention:'bounded/configurable; export/backup required'},legal:{status:'production controls drafted; jurisdiction-specific legal review still required'},nextPass:['wire verified providers/contracts where credentials exist','run end-to-end payment/staking/NFT/energy settlement tests','security/load audit and production release gate']};}
function infrastructurePass1(){return{ok:true,pass:'1/3',name:'legal-infrastructure-foundation',status:'implemented',designPrinciples:{leastPrivilege:true,consentRequired:true,jurisdictionAware:true,auditEveryAuthoritativeAction:true,idempotencyRequired:true,providerVerificationRequired:true},authorityGates:{payments:'exact-chain-receipt-and-merchant-match',settlement:'signed-authoritative-provider-record',staking:'verified-contract-and-pool-required',nftMinting:'verified-chain-provider-required',authentication:'signed-session-and-expiry-required',gridSettlement:'meter-plus-tariff-plus-interconnection-required',physicalRfSatellite:'authorized-hardware-and-provider-required'},energyPositiveArchitecture:{mode:'metered-first',positiveFlow:'measure->validate->sign->settle->audit',profitClaims:'realized-only',antiDoubleCount:'idempotency-key-plus-source-sequence',meterQuality:['measured','settled'],exportControl:'software never directly actuates grid equipment'},stakingPositiveArchitecture:{mode:'non-custodial-adapter',flow:'discover->risk-check->quote->user-authorize->provider-execute->verify->audit',yieldClaims:'no-guarantee',assetSafety:'never execute unverified pool or contract'},paymentSettlement:{mode:'fail-closed',rails:['USDC','ETH'],requiredProof:['chainId','txHash','receiptSuccess','merchantMatch','amountMatch','assetMatch'],replayDefense:'unique transaction plus intent binding'},nftMinting:{mode:'fail-closed',requiredProof:['chain','contract','tokenId','owner','receipt'],noFreeMintClaim:true},authenticationSecurity:{mode:'fail-closed',controls:['short-lived sessions','signed owner challenge','authorization boundary','rate limits','secret exclusion from QHash']},grid:{mode:'read/settle only until certified control adapter',required:['revenue-grade meter','utility/ISO tariff','interconnection agreement','authorized market participant/provider'],noDirectControl:true},rfSatellite:{mode:'receive/provider-directory until authorized hardware',required:['device capability','frequency authorization where applicable','provider credentials','transmit safety policy'],noSoftwareOnlyTransmit:true},legalReadiness:{status:'software controls only; jurisdiction/provider counsel still required',requiredBeforeProduction:['terms and privacy notices','consumer/refund disclosures','KYC/AML where legally applicable','staking/securities/financial-product review where applicable','energy interconnection and market rules','RF spectrum/device authorization','tax/accounting treatment'],records:'tamper-evident application audit plus authoritative provider receipts'},nextPass:['signed adapter envelopes and provider attestation schema','energy meter/tariff settlement adapter','staking contract/pool verification adapter','NFT mint receipt adapter','authenticated server-side QHash ingestion']}}
function retryPlan(){return{ok:true,policy:'bounded-retry',maxAttempts:3,backoffSeconds:[1,3,5],retryable:['provider_timeout','provider_unavailable','rate_limited','temporary_network_error'],nonRetryable:['invalid_input','unauthorized','forbidden','invalid_receipt','settlement_rejected'],onExhausted:'safe-local-fallback-with-stale-label'}}
function infrastructureRecovery(){return{ok:true,version:VERSION,mode:'safe-fail-open-where-non-authoritative',policy:{availability:'continue on safe local/static/reference fallbacks',authority:'never infer payment, ownership, settlement, staking, minting, physical transmission, or authentication success'},recoveryTargets:{ui:{enabled:true,fallback:'render recovery data and retry controls'},catalog:{enabled:true,fallback:'local server catalog'},search:{enabled:true,fallback:'local catalog search'},radio:{enabled:true,fallback:'provider directory/cached metadata'},physics:{enabled:true,fallback:'reference calculations only'},qhash:{enabled:true,fallback:'local SHA-256 with persistence retry'},energy:{enabled:true,fallback:'metered-input model only'},telemetry:{enabled:true,fallback:'validate/hash locally; queue semantics only'},payments:{enabled:true,fallback:'quote/receipt preparation only; settlement remains exact-chain-verified'},staking:{enabled:true,fallback:'adapter status/preview only'},qrnft:{enabled:true,fallback:'preview/customize/price flow only'},rfSatcom:{enabled:true,fallback:'directory/device-provider launcher only'}},healthSignals:{staleData:true,providerOutageVisible:true,retryableFailures:true,blankScreenRecovery:true},nextActions:['retry transient provider calls with bounded backoff','use local/static data when authoritative provider data is unavailable','label stale/unverified state at every boundary','keep security and settlement fail-closed']}}
function infrastructureBaseline(){const x={...INFRASTRUCTURE_BASELINE,generatedAt:INFRASTRUCTURE_BASELINE.generatedAt(),capacityStatement:'Designed for horizontal/provider-backed expansion; no claim of infinite storage, infinite energy, guaranteed profit, or guaranteed uptime.'};return {...x,qhash:qhash(JSON.stringify(x))}}
function verificationCenter(input={}){
  const b=input||{}, now=new Date().toISOString();
  const checks={
    rfSatelliteTelecom:{required:['deviceId','provider','authorization','capabilityAttestation'],status:'ready_for_real_attestation'},
    hologram:{required:['deviceId','provider','displayCapabilityAttestation'],status:'ready_for_real_attestation'},
    energy:{required:['meterId','meterReadings','tariff','interconnection','settlement'],status:'ready_for_real_settlement'},
    staking:{required:['chainId','pool','contract','provider','executionReceipt'],status:'ready_for_real_receipt'},
    multiverse:{required:['dataset','source','timestamp','method','independentEvidence'],status:'research-data-verifiable-only'},
    retrocausal:{required:['dataset','source','timestamp','method','independentEvidence'],status:'research-data-verifiable-only'}
  };
  const supplied=Object.keys(checks).reduce((o,k)=>{
    const x=b[k];
    o[k]={...checks[k],supplied:Boolean(x&&typeof x==='object'&&Object.keys(x).length),verified:false};
    return o;
  },{});
  return {ok:true,version:VERSION,generatedAt:now,mode:'evidence-gated-verification',checks:supplied,
    rule:'Only cryptographically or provider-verifiable evidence can change verified:false to verified:true; software never self-attests physical hardware, financial settlement, staking execution, or multiverse/retrocausal claims.',
    infrastructure:{failClosed:true,idempotency:true,qhash:'SHA-256',audit:true,replayProtection:true,leastPrivilege:true,providerAttestation:true},
    inHouse:{adapters:true,evidenceSchemas:true,validation:true,receiptBinding:true,settlementModel:true,hardwareCapabilityModel:true, researchEvidenceModel:true},
    capacity:{horizontalScaling:'provider/plan dependent',queueSafe:'bounded processing',storage:'durable provider required for persistence',hardware:'external device/provider required'},
    next:'submit real provider/device/chain evidence to the matching verifier; never mark evidence verified by configuration alone.'};
}

function qrnftStatus(){return{ok:true,version:VERSION,product:'QRNFT',priceUsd:11,cap:96000,network:'Base Mainnet',chainId:8453,flow:['create','customize','preview','price','authorize','pay','verify','issue'],qhash:'SHA-256',paymentRails:['USDC','ETH'],minting:{mode:'fail-closed',requires:['verified chain receipt','contract','tokenId','owner'],status:'provider/chain execution required'},ownership:'never claimed until verified chain receipt',idempotency:'intent-bound'}}
function musicStatus(){return{ok:true,version:VERSION,surface:'music',providers:{catalog:'MusicBrainz',archive:'Internet Archive where rights permit'},search:true,artistOriginalIntake:true,qhash:'SHA-256',rights:'license/provider evidence required',playback:'provider-dependent',downloads:'only when provider permits',ownership:'not inferred from metadata',truth:'catalog metadata does not itself grant recording or composition rights'}}
function radioStatus(){return{ok:true,version:VERSION,surface:'QuantumRadio',providers:{amfm:'Radio Browser',tv:'IPTV-org',movies:'Internet Archive',music:'MusicBrainz',satcom:'Groundstation.space',video:'Jitsi'},communications:{call:'device tel scheme',text:'device sms scheme',video:'provider-backed room'},dsp:{referenceHz:7.83,audioHz:[7.83,440,1000],rfTransmit:false},hardware:{rf:true,satellite:true,nir:true,laser:true,hologram:true,physicalDeviceRequired:true},qhash:'SHA-256',truth:'browser software provides provider directories and device launchers; physical RF/satellite/NIR/laser/hologram transmission requires authorized hardware/providers'}}
async function musicSearch(q,limit=10){const query=String(q||'').trim();if(!query)return{ok:false,error:'query_required'};const n=Math.min(25,Math.max(1,Number(limit)||10));const url='https://musicbrainz.org/ws/2/recording/?query='+encodeURIComponent(query)+'&fmt=json&limit='+n;const z=await fetch(url,{headers:{'User-Agent':'Quantum24/48 (quantum24-gains)'}});if(!z.ok)throw Error('music_provider_http_'+z.status);const j=await z.json();const recordings=(j.recordings||[]).map(x=>({id:x.id,title:x.title,artist:(x['artist-credit']||[]).map(a=>a.name||a.artist?.name).filter(Boolean).join(', '),lengthMs:x.length||null,score:x.score||null,source:'MusicBrainz'}));return{ok:true,query,provider:'MusicBrainz',count:recordings.length,recordings,rights:'metadata discovery only; playback/download requires provider and rights authorization',qhash:qhash(JSON.stringify(recordings))}}
function qrnftPrepare(input={}){const b=input||{},name=String(b.name||'Quantum24 QRNFT').slice(0,120),description=String(b.description||'').slice(0,1000),owner=String(b.owner||'').toLowerCase(),contract=String(b.contract||'').toLowerCase(),chainId=Number(b.chainId||8453),priceUsd=Number(b.priceUsd||11);if(!Number.isFinite(priceUsd)||priceUsd<0.01||priceUsd>MAX)return{ok:false,error:'invalid_price'};if(owner&&!/^0x[a-f0-9]{40}$/.test(owner))return{ok:false,error:'invalid_owner'};const intent={id:'QRNFT-'+crypto.randomBytes(12).toString('hex'),name,description,owner:owner||null,contract:contract||null,chainId,priceUsd,createdAt:new Date().toISOString(),status:'preview_only'};intent.qhash=qhash(JSON.stringify(canonicalValue(intent)));return{ok:true,intent,gate:{authorized:false,paid:false,receiptVerified:false,minted:false},next:['authorize','create payment intent','verify exact receipt','execute provider/chain mint','verify tokenId+owner','issue receipt'],truth:'This endpoint prepares a real QRNFT issuance request but does not claim a mint until a chain/provider receipt is verified.'}}

function expansionStatus(){return{ok:true,version:VERSION,mode:'production-expansion',surfaces:{quantum24:true,qrnft:true,music:true,radio:true,qhash:true,energy:true,community:true,library:true,pwa:true},scaling:{horizontal:'provider/plan dependent',statelessCore:true,queueSafe:true,bodyLimitBytes:MAX_BODY_BYTES,rpcFailover:true},integrity:{qhash:'SHA-256',canonicalInputs:true,secretsExcluded:true,auditEvents:true,replayProtection:true,idempotency:true},payments:{network:'Base Mainnet',chainId:8453,verifiedRails:['USDC','ETH'],exactReceipt:true},qrnft:{prepare:true,customize:true,preview:true,authorizationGate:true,paymentGate:true,receiptGate:true,mintClaimGate:true},music:{providerSearch:true,rightsGate:true,originalIntake:true,metadataQHash:true},radio:{providerDirectory:true,amfm:true,tv:true,music:true,movies:true,video:true,deviceCallingTexting:true,physicalRfGate:true,satelliteGate:true,hologramGate:true},energy:{meteredOnly:true,settlementRequired:true,softwareCreatesEnergy:false},truthBoundary:'Expansion adds software capacity and verified-provider pathways; it does not manufacture external authorization, physical hardware, ownership, profit, or unsupported scientific capabilities.'}}
function hardenedSecurityStatus(){return {ok:true,version:VERSION,mode:'production-hardened',controls:{strictTransportSecurity:true,nosniff:true,referrerPolicy:true,permissionsPolicy:true,frameAncestorsBlocked:true,baseUriBlocked:true,contentSecurityPolicy:true,noStore:true,requestBodyLimitBytes:MAX_BODY_BYTES,rpcTimeoutMs:7000,priceFeedTimeoutMs:5000,providerRetries:1,replayProtection:true,idempotency:true,exactReceiptVerification:true,failClosedPayments:true,failClosedQrNft:true,failClosedStaking:true,externalHardwareAttestationRequired:true},secrets:{notReturnedByQHash:true},errors:{providerFailuresLabeled:true,unsupportedExecutionBlocked:true},truth:'Hardening improves application security and integrity; it does not create authorization for external providers or physical hardware.'}}
function verificationChecklist(){
  return {ok:true,version:VERSION,productionGate:true,
    rfSatelliteTelecom:'authorization + device/provider attestation',
    hologram:'device/display provider attestation',
    energy:'revenue-grade meter + tariff + interconnection + signed settlement',
    staking:'verified contract/pool + user authorization + execution receipt',
    multiverse:'independent dataset/source/method evidence only; no physical-access claim',
    retrocausal:'independent reproducible evidence only; no causal reversal claim',
    qhash:'SHA-256 every authoritative evidence envelope',
    failClosed:true};
}

if(p==='/api/qrnft/status'&&req.method==='GET')return json(res,200,qrnftStatus());
if(p==='/api/qrnft/prepare'&&req.method==='POST'){try{return json(res,201,qrnftPrepare(await body(req)))}catch(e){return json(res,400,{ok:false,error:'qrnft_prepare_failed'})}}
if(p==='/api/music/status'&&req.method==='GET')return json(res,200,musicStatus());
if(p==='/api/music/search'&&req.method==='GET'){try{return json(res,200,await musicSearch(u.searchParams.get('q'),u.searchParams.get('limit')))}catch(e){return json(res,502,{ok:false,error:e.message||'music_provider_unavailable'})}}
if(p==='/api/radio/status'&&req.method==='GET')return json(res,200,radioStatus());
if(p==='/api/full-surface-status'&&req.method==='GET')return json(res,200,{ok:true,version:VERSION,quantum24:v44SurfaceStatus(req),qrnft:qrnftStatus(),music:musicStatus(),radio:radioStatus()});
if(p==='/api/verification/center'&&req.method==='GET')return json(res,200,verificationCenter());
if(p==='/api/verification/center'&&req.method==='POST'){try{return json(res,200,verificationCenter(await body(req)))}catch(e){return json(res,400,{ok:false,error:'invalid_verification_evidence'})}}
if(p==='/api/verification/checklist'&&req.method==='GET')return json(res,200,verificationChecklist());
if(p==='/api/quantum/max-upgrade'&&req.method==='GET')return json(res,200,quantumMaxUpgrade());
if(p==='/api/quantum/physical-infrastructure'&&req.method==='GET')return json(res,200,quantumPhysicalInfrastructure());
if(p==='/api/grid/quantum-gate'&&req.method==='GET')return json(res,200,gridQuantumGate());
if(p==='/api/quantum/next-max'&&req.method==='GET')return json(res,200,quantumNextMax());
if(p==='/api/quantum/finalization'&&req.method==='GET')return json(res,200,quantumFinalization());
if(p==='/api/quantum/operability'&&req.method==='GET')return json(res,200,quantumOperability());
if(p==='/api/quantum/ultimate'&&req.method==='GET')return json(res,200,quantumUltimate());
if(p==='/api/grid/positive-record'&&req.method==='POST'){try{const x=validateGridPositiveRecord(await body(req));await recordQHashEvent({internal:true,eventType:'grid_positive_energy',surface:'grid',actorKind:'server',data:x});return json(res,200,x)}catch(e){return json(res,400,{ok:false,error:e.message||'grid_record_rejected'})}}

if(p==='/api/energy/settlement/realized'&&req.method==='POST'){try{const x=validateRealizedEnergySettlement(await body(req));await recordQHashEvent({internal:true,eventType:'realized_energy_settlement',surface:'energy-settlement',actorKind:'server',data:x});return json(res,200,x)}catch(e){return json(res,400,{ok:false,error:e.message||'settlement_rejected'})}}

if(p==='/api/infrastructure/pass3'&&req.method==='GET')return json(res,200,infrastructurePass3());
if(p==='/api/energy/measured-gain'&&req.method==='POST'){try{const b=await body(req);const x=measurableEnergyGain(b);await recordQHashEvent({internal:true,eventType:'measured_energy_gain',surface:'energy-gate',actorKind:'server',data:x});return json(res,200,x)}catch(e){return json(res,400,{ok:false,error:e.message||'invalid_meter_telemetry'})}}
if(p==='/api/infrastructure/pass1'&&req.method==='GET')return json(res,200,infrastructurePass1());
if(p==='/api/infrastructure/pass2'&&req.method==='GET')return json(res,200,infrastructurePass2());
if(p==='/api/infrastructure/fallbacks'&&req.method==='GET')return json(res,200,availabilityFallbacks());
if(p==='/api/infrastructure/recovery'&&req.method==='GET')return json(res,200,infrastructureRecovery());
if(p==='/api/infrastructure/retry-plan'&&req.method==='GET')return json(res,200,retryPlan());
if(p==='/api/infrastructure/adapters'&&req.method==='GET')return json(res,200,{ok:true,...adapterHealth()});
if(p==='/api/infrastructure/telemetry/validate'&&req.method==='POST'){let x;try{x=await body(req)}catch(e){return json(res,400,{ok:false,error:'invalid_json'})}return json(res,200,telemetryValidate(x));}
if(p==='/api/infrastructure/settlement/status'&&req.method==='GET')return json(res,200,{ok:true,...settlementAdapterStatus()});
if(p==='/api/infrastructure/security/status'&&req.method==='GET')return json(res,200,{ok:true,...securityHealth()});
if(p==='/api/security/hardened'&&req.method==='GET')return json(res,200,hardenedSecurityStatus());
if(p==='/api/expansion/status'&&req.method==='GET')return json(res,200,expansionStatus());
if(p==='/api/infrastructure/release/status'&&req.method==='GET')return json(res,200,{ok:true,...releaseAudit()});
if(p==='/api/infrastructure/upgrades'&&req.method==='GET')return json(res,200,upgradeMatrix());
if(p==='/health'&&req.method==='GET')return json(res,200,{ok:true,service:'quantum24-gains',version:VERSION,status:'healthy',releasePass:'5/5'});
if(p==='/api/infrastructure/settlement/telemetry'&&req.method==='POST'){let x;try{x=await body(req)}catch(e){return json(res,400,{ok:false,error:'invalid_json'})}return json(res,200,validateSettlementTelemetry(x));}
if(p==='/api/infrastructure/baseline'&&req.method==='GET')return json(res,200,{ok:true,...infrastructureBaseline()});
if(p==='/api/public-status'&&req.method==='GET')return json(res,200,{ok:true,service:'quantum24-gains',version:VERSION,publicFlows:{clicks:true,qhash:true,energyAccounting:true,payments:true,media:true,telecom:true},energy:{mode:'metered',physicalGenerationRequired:true,gridConnected:false,positiveExportMeansMeasuredGenerationExceedsLoad:true},persistence:{qhash:'Supabase-backed when configured',eternal:false},userScope:'public'});
if(p==='/api/action'&&req.method==='POST'){try{const b=await body(req);b.ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();b.eventType=String(b.eventType||'action');return json(res,200,await recordQHashEvent(b))}catch(e){return json(res,400,{ok:false,error:'action_rejected'})}}
if(p==='/api/energy/state'&&req.method==='GET')return json(res,200,energyState());
if(p==='/api/energy/calculate'&&req.method==='POST'){try{const b=await body(req);const v=energyVector(b);const q=qhash(JSON.stringify(canonicalValue(v)));await recordQHashEvent({internal:true,eventType:'energy_vector_calculated',surface:'energy-gate',actorKind:'server',data:{...v,qhash:q}});return json(res,200,{ok:true,...v,qhash:q,physicalGeneration:false})}catch(e){return json(res,400,{ok:false,error:'invalid_energy_vector'})}}
if(p==='/api/qhash-data'&&req.method==='POST'){try{const b=await body(req);const q=quantifyPayload(b);await recordQHashEvent({internal:true,eventType:'data_quantified',surface:'qhash-data',actorKind:'server',data:{kind:q.kind,byteLength:q.byteLength,bitLength:q.bitLength,byteQHash:q.byteQHash,bitQHash:q.bitQHash,canonicalQHash:q.canonicalQHash,vectorQHash:q.vectorQHash}});return json(res,200,q)}catch(e){return json(res,400,{ok:false,error:e.message||'quantification_failed'})}}
if(p==='/api/qhash-capabilities'&&req.method==='GET')return json(res,200,{ok:true,algorithm:'SHA-256',representations:['UTF-8 bytes','binary bits','canonical JSON','sampled byte vector'],eventCoverage:['click','input','select','summary','wallet','payment','search','download','media','share','vault','data_quantified','onchain_payment_verified'],onchain:'Base payment events are linked to verified transaction hashes; arbitrary QHash anchoring requires a funded signer and is not claimed here.',sensors:{visibleLight:'software/browser-observable only',IR:false,NIR:false,reason:'requires physical sensor hardware'}});if(p==='/api/qhash'&&req.method==='POST'){const b=await body(req);return json(res,200,{ok:true,qhash:qhash(JSON.stringify(b)),algorithm:'SHA-256',scope:'application fingerprint; not a blockchain transaction hash'});}
if(p==='/api/selftest'&&req.method==='GET'){const checks={health:true,ready:true,catalog:Array.isArray(bankrTokenMatrix)&&bankrTokenMatrix.length===25,qhash:typeof qhash==='function',paymentRails:['USDC','ETH'],physicsReference:7.83,serverClock:new Date().toISOString()};return json(res,200,{ok:Object.values(checks).every(Boolean),version:VERSION,checks})}
if(p==='/api/device'&&req.method==='GET')return json(res,200,{ok:true,serverSupported:true,clientProfile:{responsive:true,touchTargets:true,locale:'navigator.language',reducedMotion:'prefers-reduced-motion',safeArea:true}});
if(p==='/api/physics'&&req.method==='GET')return json(res,200,{ok:true,knownReferences:{schumannFundamentalHz:7.83},calculations:['frequency','period','wavelength','hash-derived identifiers'],claimBoundary:'software calculations and references only; no physical energy generation/access claimed'});
if(p==='/api/catalog'||p==='/api/pricing')return json(res,200,{ok:true,...catalog()});
if(p==='/api/live')return json(res,200,await live());
if(p==='/api/live-pricing')return json(res,200,{ok:true,network:'Base Mainnet',chainId:8453,ethUsd:await ethPrice(),usdcUsd:1,productPricing:'fixed USD catalog',updatedAt:new Date().toISOString(),cacheSeconds:30});
if(p==='/api/eth-price')return json(res,200,{ok:true,usd:await ethPrice(),network:'Base Mainnet',updatedAt:new Date().toISOString()});
if(p==='/api/intent'&&req.method==='POST'){const b=await body(req),x=await quote(String(b.product||''),b.customUsd,String(b.token||'USDC'));if(!x)return json(res,400,{ok:false,error:'invalid_product_or_amount'});const iq=await x;await recordQHashEvent({internal:true,eventType:'payment_intent',surface:'payment',actorKind:'anonymous',data:{intentQHash:iq.qhash,product:iq.product,amountUsd:iq.amountUsd,token:iq.token}});return json(res,201,{ok:true,status:'ready',...iq,message:'Ready for wallet confirmation. No funds moved.'})}
if(p==='/api/verify'&&req.method==='POST')return json(res,200,await verify(await body(req)));
if(p==='/api/order'&&req.method==='GET'){const tx=String(u.searchParams.get('tx')||'').toLowerCase();return json(res,200,{ok:true,order:orders.get(tx)||null})}
if(p==='/api/receipt'&&req.method==='GET'){const tx=String(u.searchParams.get('tx')||'').toLowerCase();if(!/^0x[a-f0-9]{64}$/.test(tx))return json(res,400,{ok:false,error:'invalid_tx_hash'});return json(res,200,{ok:true,receipt:orders.get(tx)||null,onchain:await txLookup(tx)})}
if(p==='/api/search'&&req.method==='GET'){const q=String(u.searchParams.get('q')||'').trim().toLowerCase();if(/^0x[a-f0-9]{64}$/.test(q)){const tx=await txLookup(q);const order=orders.get(q)||null;return json(res,200,{ok:true,type:'transaction',tx,order,ownership:order?{ownerWallet:order.from,merchantWallet:MERCHANT,paidOnchain:order.status==='paid',chain:'Base Mainnet'}:{onchainObserved:!!tx}});}const download='/download/quantum-catalog.json';const results=[...Object.entries(products).filter(([n,v])=>n.toLowerCase().includes(q)||String(v).includes(q)).map(([product,amountUsd])=>({kind:'quantum',product,amountUsd,action:'pay',paymentRail:'USDC_or_ETH',downloadUrl:download})),...Object.entries(aiPoints).filter(([n,x])=>n.toLowerCase().includes(q)||String(x.points).includes(q)).map(([product,x])=>({kind:'ai',product,amountUsd:x.usd,points:x.points,downloadUrl:download})),...bankrTokenMatrix.filter(x=>x.includes(q)).map(token=>({kind:'bankr-token',token,status:'app-defined; live payment route not independently verified',downloadUrl:download}))];return json(res,200,{ok:true,type:'quantum_search',query:q,downloadUrl:download,results})}
if(p==='/api/v44/status'&&req.method==='GET')return json(res,200,v44SurfaceStatus(req));
if(p==='/api/pass2/verify'&&req.method==='GET')return json(res,200,pass2Verification());
if(p==='/api/capability-infrastructure'&&req.method==='GET')return json(res,200,capabilityInfrastructure());
if(p==='/api/user/ops'&&req.method==='GET')return json(res,200,quantumUserOps(req));
if(p==='/api/schumann/profile'&&req.method==='GET')return json(res,200,schumannProfileStatus(req));
if(p==='/api/live-values'&&req.method==='GET')return json(res,200,liveValueStatus());
if(p==='/api/library/status'&&req.method==='GET')return json(res,200,artistLibraryStatus());
if(p==='/api/library/artist-original'&&req.method==='POST'){try{return json(res,201,artistOriginalIntake(await body(req)))}catch(e){return json(res,400,{ok:false,error:e.message||'library_intake_failed'})}}
if(p==='/api/health'&&req.method==='GET')return json(res,200,{ok:true,service:'quantum24',version:VERSION,chain:'base',payments:['USDC','ETH'],uptime:'continuous'});
if(p==='/api/owner/challenge'&&req.method==='POST')return json(res,200,{ok:true,...challenge()});
if(p==='/api/owner/verify'&&req.method==='POST')return json(res,200,await ownerVerify(await body(req)));
if(p==='/api/owner/purchases'&&req.method==='GET'){if(!ownerOK(req))return json(res,401,{ok:false,error:'owner_auth_required'});return json(res,200,{ok:true,owner:MERCHANT,localOrders:[...orders.values()].slice(-500).reverse(),onchain:await scanPurchases(u.searchParams.get('blocks'))})}
if(p==='/download/quantum-catalog.json')return send(res,200,mime['.json'],JSON.stringify(catalog(),null,2));
if(p.startsWith('/download/quantum-string/')){const key=decodeURIComponent(p.slice('/download/quantum-string/'.length)).replace(/\\.json$/,'');const token=bankrTokenMatrix.find(x=>slug(x)===slug(key));if(!token)return json(res,404,{ok:false,error:'quantum_string_not_found'});return send(res,200,mime['.json'],JSON.stringify({kind:'quantum-string',token,active:true,interactive:true,paymentRails:['USDC','ETH'],network:'Base Mainnet',merchant:MERCHANT,qhash:qhash(token+'|'+MERCHANT+'|'+VERSION),downloadedAt:new Date().toISOString()},null,2))}
if(req.method==='GET'){let file=p==='/index.html'||p==='/'?'index.html':path.basename(p);if(p==='/quantum-radio.html')return send(res,200,'text/html; charset=utf-8',fs.readFileSync(path.join(ROOT,'quantum-radio.html')));
    if(p==='/qhash-sdk.js')return send(res,200,'application/javascript; charset=utf-8',fs.readFileSync(path.join(ROOT,'qhash-sdk.js')));if(p==='/manifest.json')file='manifest.webmanifest';if(!['index.html','manifest.webmanifest','sw.js','icon.svg','qhash-sdk.js'].includes(file))return send(res,404,'text/plain; charset=utf-8','Not found');const f=path.join(ROOT,file);return fs.readFile(f,(e,d)=>e?send(res,404,'text/plain; charset=utf-8','Quantum24 file not found'):send(res,200,mime[path.extname(f)]||'application/octet-stream',d))}
return json(res,404,{ok:false,error:'not_found'})}catch(e){console.error(e);return json(res,500,{ok:false,error:'server_error',message:e.message})}});
server.keepAliveTimeout=65000;
server.headersTimeout=70000;
const shutdown=signal=>{console.log('Quantum24 graceful shutdown '+signal);server.close(()=>process.exit(0));setTimeout(()=>process.exit(1),25000).unref()};
process.once('SIGTERM',()=>shutdown('SIGTERM'));
process.once('SIGINT',()=>shutdown('SIGINT'));
process.on('uncaughtException',e=>{console.error('Quantum24 uncaughtException',e);shutdown('uncaughtException')});
process.on('unhandledRejection',e=>{console.error('Quantum24 unhandledRejection',e);shutdown('unhandledRejection')});
server.listen(PORT,'0.0.0.0',()=>console.log('Quantum24 '+VERSION+' listening on '+PORT));
