const TOKENS=[["Rollin","0x622e4536a4B3D5A3AcB99A70bDFC50a3255d3bA3"],["Balloon","0x494301facc434ca703239e3e1e5def31fdc20ba3"],["Caffeine","0x5a69d0cc5783bd15c437dc329d78319325d13ba3"],["Zai","0x05e4c8b357da5981496cc7b2b0b8ea3956212ba3"],["Telp","0x22ffa503e90c651cb53e3f88deafc80160c9fba3"],["Auto","0x910cb6ce72a2ee7b1c9d093d5b09aed7f19f8ba3"],["Aeth","0x8c7cffbdd51be8c43300f38f052ccdaac59f0ba3"],["Wo","0x7811d40ec95015c4571663a2eaaeca58c4412ba3"],["Flaw","0xe9bd329a1ff8c56c9f44a937863983ec5b81aba3"],["Emrld","0x4b89c4263e1dc7c843482b85bff12b142ac4aba3"],["Rev","0xaf4721ead1b366b88d21d6a0bfec7b25cb118ba3"],["Blzet","0xad4f3857808a7c3b420c87d7cfabfe3934c18ba3"]],TREASURY="0x13653b6b8bd4b274da565faf6fa894e3418a6d10";
const products=[
{id:1,name:"Rollin Starter Bundle",cat:"Featured",price:120,icon:"✦",desc:"Launch bundle with member perks.",tag:"FEATURED",repeat:true},
{id:2,name:"Caffeine Daily Pack",cat:"Caffeine",price:75,icon:"☕",desc:"Consumable bundle designed for repeat purchase.",tag:"REPEAT",repeat:true},
{id:3,name:"Aeth Tech Pass",cat:"Digital",price:250,icon:"◈",desc:"Digital access product architecture.",tag:"DIGITAL"},
{id:4,name:"Auto Care Credit",cat:"Auto",price:400,icon:"◉",desc:"Service-credit marketplace product.",tag:"SERVICE"},
{id:5,name:"Emrld Member Drop",cat:"Drops",price:320,icon:"◆",desc:"Limited member drop with explicit inventory state.",tag:"DROP"},
{id:6,name:"Balloon Creator Kit",cat:"Balloon",price:90,icon:"○",desc:"Creator bundle with referral sharing.",tag:"SHARE"},
{id:7,name:"Telp Connect Pack",cat:"Telp",price:160,icon:"⌁",desc:"Communications service product.",tag:"SERVICE"},
{id:8,name:"Blzet Collectible",cat:"Collectibles",price:210,icon:"✺",desc:"Collectible/access utility.",tag:"ACCESS"}];
const nav=[["home","⌂","Home"],["shop","▦","Shop"],["drops","◈","Drops"],["rewards","★","Rewards"],["wallet","◉","Wallet"],["profile","●","Profile"],["gaia","♧","Gaia"],["merchant","◇","Sell"]];
const defaults={cart:[],orders:[],rewards:0,tier:"Free",ref:"ROLLIN-"+Math.random().toString(36).slice(2,8).toUpperCase(),theme:"dark",favorites:[],newsletter:false};
let state={...defaults,...JSON.parse(localStorage.getItem("rollin-state")||"{}")};
const el=s=>document.querySelector(s),save=()=>localStorage.setItem("rollin-state",JSON.stringify(state)),money=n=>n.toLocaleString()+" ROLLIN";
const navHtml=()=>nav.map(([id,ic,label])=>'<button class="nav-link" data-nav="'+id+'"><span>'+ic+'</span><span>'+label+'</span></button>').join("");
el("#desktopNav").innerHTML=navHtml();el("#mobileNav").innerHTML=navHtml();
document.addEventListener("click",e=>{const b=e.target.closest("[data-nav]");if(b)location.hash=b.dataset.nav;const a=e.target.closest("[data-add]");if(a)addToCart(+a.dataset.add);const f=e.target.closest("[data-fav]");if(f)toggleFav(+f.dataset.fav);const s=e.target.closest("[data-share]");if(s)shareProduct(+s.dataset.share);});
el("#walletBtn").onclick=()=>openModal('<div class="modal-head"><div><div class="eyebrow">WALLET</div><h2>Verification gate</h2></div><button class="close" onclick="closeModal()">×</button></div><p class="muted">Rollin never invents balances, prices, confirmations or returns. The supplied addresses are stored as configuration, but the production network is not verified in this deployment.</p><div class="notice"><strong>Primary:</strong> Rollin<br><code>'+TOKENS[0][1]+'</code><br><br><strong>Treasury:</strong><br><code>'+TREASURY+'</code></div>');
el("#themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=state.theme;save()};
window.addEventListener("hashchange",render);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
function render(){const page=(location.hash.slice(1)||"home").split("?")[0];document.querySelectorAll("[data-nav]").forEach(x=>x.classList.toggle("active",x.dataset.nav===page));({home,shop,drops,rewards,wallet,profile,cart,checkout,merchant,gaia}[page]||home)();window.scrollTo(0,0)}
function shell(content,title=""){el("#view").innerHTML='<div class="page">'+content+'<div class="footer"><strong>Rollin</strong> is a commerce platform concept. Payments, settlement and blockchain verification remain disabled until real production credentials/network configuration are connected. No investment, earnings or asset-appreciation promises are made.</div></div>';document.title=title?title+" — Rollin":"Rollin — Shop. Earn. Unlock. Repeat."}
function productCard(p){const fav=state.favorites.includes(p.id);return '<article class="card"><div class="product-art">'+p.icon+'<button class="fav '+(fav?"on":"")+'" data-fav="'+p.id+'" aria-label="Favorite">'+(fav?"♥":"♡")+'</button></div><div class="card-body"><span class="tag">'+p.tag+'</span><h3>'+p.name+'</h3><p class="muted">'+p.desc+'</p><div class="price">'+money(p.price)+' <small>· demo catalog</small></div><div class="card-actions"><button class="primary" data-add="'+p.id+'">Add</button><button class="secondary" data-share="'+p.id+'">Share</button></div></div></article>'}
function home(){shell('<section class="hero"><div class="hero-card"><div class="eyebrow">ROLLIN COMMERCE OS</div><h1>SHOP.<br>EARN.<br>REPEAT.</h1><p>A fast, mobile-first commerce hub combining products, memberships, drops, rewards, referrals and merchant tools.</p><div class="hero-actions"><button class="primary" onclick="location.hash=\'shop\'">Explore Shop →</button><button class="secondary" onclick="location.hash=\'merchant\'">Sell on Rollin</button></div><div class="trust-row"><span>✓ Mobile-first</span><span>✓ PWA-ready</span><span>✓ Human-first</span></div></div><div class="wallet-card"><div><div class="eyebrow">ROLLIN WALLET</div><div class="balance">—</div><div class="status"><span class="dot"></span> Verification required</div></div><div><p class="muted">Real network data only. No fabricated balances.</p><button class="secondary" onclick="location.hash=\'wallet\'">Open Wallet</button></div></div></section><section class="section stats"><div class="stat">Cart<strong>'+state.cart.length+'</strong></div><div class="stat">Orders<strong>'+state.orders.length+'</strong></div><div class="stat">Rewards<strong>'+state.rewards+'</strong></div><div class="stat">Tier<strong>'+state.tier+'</strong></div></section><section class="section"><div class="section-head"><h2>Trending</h2><button class="secondary" onclick="location.hash=\'shop\'">All products</button></div><div class="grid">'+products.slice(0,4).map(productCard).join("")+'</div></section><section class="section feature-grid"><div class="feature"><div class="feature-icon">↻</div><h3>Repeat commerce</h3><p class="muted">Subscriptions, replenishment and member benefits create useful return loops.</p></div><div class="feature"><div class="feature-icon">↗</div><h3>Built to spread</h3><p class="muted">Share links and referrals are first-class product actions.</p></div><div class="feature"><div class="feature-icon">◇</div><h3>Merchant engine</h3><p class="muted">Catalog, campaigns, loyalty and analytics architecture are ready for a real backend.</p></div></section><section class="section newsletter"><div><div class="eyebrow">ROLLIN SIGNAL</div><h2>Get drops and new-store alerts</h2><p class="muted">Optional email capture. No spam promises.</p></div><div class="inline-form"><input id="email" class="search" type="email" placeholder="you@example.com"><button class="primary" onclick="subscribe()">Join</button></div></section>')}
function shop(){shell('<div class="section-head"><div><div class="eyebrow">MARKETPLACE</div><h2>Discover your next buy</h2></div><button class="secondary" onclick="location.hash=\'cart\'">Cart ('+state.cart.length+')</button></div><div class="toolbar"><input id="search" class="search" placeholder="Search products, categories…"><select id="filter" class="search"><option value="all">All categories</option><option>Featured</option><option>Caffeine</option><option>Digital</option><option>Auto</option><option>Drops</option><option>Balloon</option><option>Telp</option><option>Collectibles</option></select><button class="secondary" onclick="location.hash=\'drops\'">Live drops</button></div><div id="shopGrid" class="grid">'+products.map(productCard).join("")+'</div>');const filter=()=>{const q=el("#search").value.toLowerCase(),c=el("#filter").value;el("#shopGrid").innerHTML=products.filter(p=>(c==="all"||p.cat===c)&&(p.name+" "+p.cat+" "+p.desc).toLowerCase().includes(q)).map(productCard).join("")};el("#search").oninput=filter;el("#filter").onchange=filter}
function drops(){shell('<div class="drop-banner"><div class="eyebrow">DROP CENTER</div><h2>Member Drop</h2><p class="muted">Time and inventory are application data, never manufactured scarcity.</p><div class="count">LIVE</div></div><div class="grid">'+products.filter(p=>p.tag==="DROP").map(productCard).join("")+'</div><section class="section notice">Referral route: <strong>'+location.origin+location.pathname+'#drops?ref='+state.ref+'</strong></section>')}
function rewards(){shell('<div class="eyebrow">LOYALTY</div><h2>Rewards that reward real use</h2><p class="muted">Credits and benefits—not promises of token appreciation.</p><section class="section stats"><div class="stat">Credits<strong>'+state.rewards+'</strong></div><div class="stat">Membership<strong>'+state.tier+'</strong></div><div class="stat">Favorites<strong>'+state.favorites.length+'</strong></div><div class="stat">Referral<strong>'+state.ref.slice(-6)+'</strong></div></section><section class="section split"><div class="feature"><span class="tag">MEMBERSHIP</span><h2>Rollin Member</h2><p class="muted">Early access, member pricing and enhanced platform rewards.</p><button class="primary" onclick="upgradeTier()">Choose Member</button></div><div class="feature"><span class="tag">REFERRAL</span><h2>Share & earn</h2><p class="muted">Your code: <strong>'+state.ref+'</strong></p><button class="secondary" onclick="copyText(location.origin+location.pathname+'?ref='+state.ref)">Copy referral link</button></div></section>')}
function wallet(){shell('<div class="eyebrow">WALLET</div><h2>Verified wallet layer</h2><div class="notice section"><strong>Status:</strong> network not configured. Transaction signing is intentionally disabled.</div><div class="grid section">'+TOKENS.map((t,i)=>'<div class="card"><div class="card-body"><span class="tag">'+(i?"ECOSYSTEM":"PRIMARY")+'</span><h3>'+t[0]+'</h3><p class="muted address">'+t[1]+'</p><strong>Balance unavailable</strong></div></div>').join("")+'</div>')}
function profile(){shell('<div class="eyebrow">PROFILE</div><h2>Your Rollin workspace</h2><div class="split section"><div class="feature"><h3>Referral identity</h3><p class="muted">'+state.ref+'</p><button class="secondary" onclick="copyText(state.ref)">Copy</button></div><div class="feature"><h3>Saved favorites</h3><p class="muted">'+state.favorites.length+' saved products.</p><button class="secondary" onclick="location.hash=\'shop\'">Browse</button></div></div><section class="section"><h2>Orders</h2>'+(state.orders.length?'<table class="table"><tr><th>Order</th><th>Total</th><th>Status</th></tr>'+state.orders.map(o=>'<tr><td>'+o.id+'</td><td>'+money(o.total)+'</td><td>DEMO</td></tr>').join("")+'</table>':'<div class="empty">No orders yet.</div>')+'</section>')}
function cart(){const items=state.cart.map(id=>products.find(p=>p.id===id)).filter(Boolean),total=items.reduce((a,p)=>a+p.price,0);shell('<div class="section-head"><div><div class="eyebrow">CART</div><h2>'+items.length+' item'+(items.length===1?"":"s")+'</h2></div><button class="secondary" onclick="location.hash=\'shop\'">Continue shopping</button></div>'+(items.length?'<div class="grid">'+items.map(productCard).join("")+'</div><section class="section split"><div class="feature"><h3>Total</h3><div class="balance">'+money(total)+'</div><p class="muted">Catalog totals are demo values until live merchant pricing is connected.</p></div><div class="feature"><h3>Checkout</h3><p class="muted">Payment is gated until production credentials are configured.</p><button class="primary" onclick="location.hash=\'checkout\'">Continue →</button></div></section>':'<div class="empty">Your cart is empty.</div>'))}
function checkout(){const items=state.cart.map(id=>products.find(p=>p.id===id)).filter(Boolean),total=items.reduce((a,p)=>a+p.price,0);shell('<div class="eyebrow">CHECKOUT</div><h2>Universal checkout</h2><div class="split section"><div class="feature"><h3>Order summary</h3>'+items.map(p=>'<p>'+p.name+' <strong class="float">'+money(p.price)+'</strong></p>').join("")+'<hr><h3>Total <span class="float">'+money(total)+'</span></h3></div><div class="feature"><h3>Payment gate</h3><div class="notice">Stripe/merchant payment credentials and a verified network are required before real charges can be enabled.</div><button class="primary full" onclick="createDemoOrder()">Create demo order</button></div></div>')}
function merchant(){shell('<div class="eyebrow">MERCHANT OS</div><h2>Sell on Rollin</h2><p class="muted">A commercial surface for stores, creators and service providers.</p><div class="feature-grid section">'+["Storefronts","Products & inventory","Subscriptions","Drops & campaigns","Customer loyalty","Analytics","Promoted discovery","Settlement"].map(x=>'<div class="feature"><span class="tag">READY</span><h3>'+x+'</h3><p class="muted">Backend connector required for production data.</p></div>').join("")+'</div><section class="section newsletter"><div><h2>Merchant launch list</h2><p class="muted">Collect interest before opening seller onboarding.</p></div><div class="inline-form"><input id="merchantEmail" class="search" type="email" placeholder="merchant@example.com"><button class="primary" onclick="merchantLead()">Request access</button></div></section>')}
function gaia(){shell('<div class="eyebrow">PEOPLE • PLANET • PROSPERITY</div><h2>Gaia Mode</h2><p class="muted">Human-first commerce with evidence-based impact claims.</p><section class="section stats"><div class="stat">Privacy<strong>Minimized</strong></div><div class="stat">Accessibility<strong>First-class</strong></div><div class="stat">Performance<strong>Lightweight</strong></div><div class="stat">Choice<strong>User-controlled</strong></div></section><section class="section feature-grid"><div class="feature"><h3>Clear commerce</h3><p class="muted">Transparent pricing, consent, cancellation and policies.</p></div><div class="feature"><h3>Durable web</h3><p class="muted">Static-first architecture reduces unnecessary runtime cost and resource use.</p></div><div class="feature"><h3>Real revenue</h3><p class="muted">Commerce, memberships, merchant services, promotion and digital goods—not financial promises.</p></div></section>')}
function addToCart(id){state.cart.push(id);save();toast("Added to cart");render()}
function toggleFav(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render()}
function createDemoOrder(){const items=state.cart.map(id=>products.find(p=>p.id===id)).filter(Boolean),total=items.reduce((a,p)=>a+p.price,0);if(!items.length)return toast("Cart is empty");state.orders.push({id:"DEMO-"+Date.now().toString(36).toUpperCase(),total});state.rewards+=Math.max(1,Math.floor(total/10));state.cart=[];save();toast("Demo order created");setTimeout(()=>location.hash="profile",500)}
function upgradeTier(){state.tier="Member";save();toast("Member tier selected")}
function subscribe(){const v=el("#email")?.value;if(!v||!v.includes("@"))return toast("Enter a valid email");state.newsletter=true;save();toast("You're on the Rollin list")}
function merchantLead(){const v=el("#merchantEmail")?.value;if(!v||!v.includes("@"))return toast("Enter a valid email");toast("Merchant interest saved locally")}
function shareProduct(id){const p=products.find(x=>x.id===id),url=location.origin+location.pathname+"#shop?product="+id+"&ref="+state.ref;if(navigator.share)navigator.share({title:p.name,text:"Discover this on Rollin",url}).catch(()=>{});else copyText(url);toast("Share link ready")}
function copyText(s){navigator.clipboard?.writeText(s);toast("Copied")}
function openModal(html){el("#modal").innerHTML='<div class="modal-box">'+html+'<button class="secondary full" onclick="closeModal()">Continue</button></div>';el("#modal").classList.remove("hidden")}function closeModal(){el("#modal").classList.add("hidden")}window.closeModal=closeModal;function toast(s){const t=el("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}window.upgradeTier=upgradeTier;window.createDemoOrder=createDemoOrder;window.subscribe=subscribe;window.merchantLead=merchantLead;window.copyText=copyText;window.render=render;
render();