const TOKENS=[["Rollin","0x622e4536a4B3D5A3AcB99A70bDFC50a3255d3bA3"],["Balloon","0x494301facc434ca703239e3e1e5def31fdc20ba3"],["Caffeine","0x5a69d0cc5783bd15c437dc329d78319325d13ba3"],["Zai","0x05e4c8b357da5981496cc7b2b0b8ea3956212ba3"],["Telp","0x22ffa503e90c651cb53e3f88deafc80160c9fba3"],["Auto","0x910cb6ce72a2ee7b1c9d093d5b09aed7f19f8ba3"],["Aeth","0x8c7cffbdd51be8c43300f38f052ccdaac59f0ba3"],["Wo","0x7811d40ec95015c4571663a2eaaeca58c4412ba3"],["Flaw","0xe9bd329a1ff8c56c9f44a937863983ec5b81aba3"],["Emrld","0x4b89c4263e1dc7c843482b85bff12b142ac4aba3"],["Rev","0xaf4721ead1b366b88d21d6a0bfec7b25cb118ba3"],["Blzet","0xad4f3857808a7c3b420c87d7cfabfe3934c18ba3"]],TREASURY="0x13653b6b8bd4b274da565faf6fa894e3418a6d10";
const products=[
{id:1,name:"Rollin Starter Bundle",cat:"Featured",price:120,icon:"✦",desc:"Demo commerce bundle with member perks.",tag:"DEMO"},
{id:2,name:"Caffeine Daily Pack",cat:"Caffeine",price:75,icon:"☕",desc:"Recurring-ready consumable bundle.",tag:"REPEAT"},
{id:3,name:"Aeth Tech Pass",cat:"Digital",price:250,icon:"◈",desc:"Digital access pass architecture.",tag:"DIGITAL"},
{id:4,name:"Auto Care Credit",cat:"Auto",price:400,icon:"◉",desc:"Service-credit marketplace example.",tag:"SERVICE"},
{id:5,name:"Emrld Member Drop",cat:"Drops",price:320,icon:"◆",desc:"Limited demo drop with real inventory state.",tag:"LIMITED"},
{id:6,name:"Balloon Creator Kit",cat:"Balloon",price:90,icon:"○",desc:"Creator bundle with referral-ready sharing.",tag:"SHARE"},
{id:7,name:"Telp Connect Pack",cat:"Telp",price:160,icon:"⌁",desc:"Communications service example.",tag:"SERVICE"},
{id:8,name:"Blzet Collectible",cat:"Collectibles",price:210,icon:"✺",desc:"Demo collectible/access utility.",tag:"ACCESS"}];
let state=JSON.parse(localStorage.getItem("rollin-state")||'{"cart":[],"orders":[],"rewards":0,"tier":"Free","ref":"ROLLIN-"+Math.random().toString(36).slice(2,8).toUpperCase(),"theme":"dark"}');
const nav=[["home","⌂","Home"],["shop","▦","Shop"],["drops","◈","Drops"],["rewards","★","Rewards"],["wallet","◉","Wallet"],["profile","●","Profile"],["gaia","♧","Gaia"]];
const save=()=>localStorage.setItem("rollin-state",JSON.stringify(state));
const money=n=>n.toLocaleString()+" ROLLIN";
const el=(s)=>document.querySelector(s);
function navHtml(){return nav.map(([id,ic,label])=>'<button class="nav-link" data-nav="'+id+'"><span>'+ic+'</span><span>'+label+'</span></button>').join("")}
el("#desktopNav").innerHTML=navHtml();el("#mobileNav").innerHTML=navHtml();
document.addEventListener("click",e=>{const b=e.target.closest("[data-nav]");if(b)location.hash=b.dataset.nav;const a=e.target.closest("[data-add]");if(a)addToCart(+a.dataset.add);const q=e.target.closest("[data-buy]");if(q)buyNow(+q.dataset.buy);const s=e.target.closest("[data-share]");if(s)shareProduct(+s.dataset.share);});
el("#walletBtn").onclick=()=>openModal("<div class='modal-head'><div><div class='eyebrow'>WALLET</div><h2>Network not configured</h2></div><button class='close' onclick='closeModal()'>×</button></div><p class='muted'>The supplied token addresses are stored as ecosystem configuration, but no blockchain network has been verified. No balance, price or transaction will be fabricated.</p><div class='notice'><strong>Primary:</strong> Rollin<br><code>"+TOKENS[0][1]+"</code><br><br><strong>Treasury:</strong><br><code>"+TREASURY+"</code></div><button class='primary' style='margin-top:15px;width:100%' onclick='closeModal()'>Continue in demo mode</button>");
el("#themeBtn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";document.documentElement.style.setProperty("--bg",state.theme==="light"?"#f4f6f8":"#090c11");document.body.style.background=state.theme==="light"?"#f4f6f8":"";save()};
window.addEventListener("hashchange",render);if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});
function render(){const page=location.hash.slice(1)||"home";document.querySelectorAll("[data-nav]").forEach(x=>x.classList.toggle("active",x.dataset.nav===page));({home:home,shop:shop,drops:drops,rewards:rewards,wallet:wallet,profile:profile,cart:cart,checkout:checkout,merchant:merchant,admin:admin,legal:legal,gaia:gaia}[page]||home)();window.scrollTo({top:0,behavior:"instant"})}
function shell(content,title=""){el("#view").innerHTML='<div class="page">'+content+'<div class="footer">Rollin is a commerce/loyalty experience. Crypto network, token prices and transaction verification remain disabled until the actual network configuration is verified. No investment or return promises. People, planet and prosperity remain core design constraints.</div></div>';document.title=title?title+" — Rollin":"Rollin — Shop. Earn. Unlock. Repeat."}
function gaia(){shell('<div class="eyebrow">PEOPLE • PLANET • PROSPERITY</div><h2>Gaia Mode</h2><p class="muted">A human-first commerce layer designed around durable user value and responsible planetary impact.</p><section class="section stats"><div class="stat">Human value<strong>Protected</strong></div><div class="stat">Privacy<strong>Minimized</strong></div><div class="stat">Accessibility<strong>First-class</strong></div><div class="stat">Performance<strong>Budgeted</strong></div></section><section class="section feature-grid"><div class="feature"><div class="feature-icon">♥</div><h3>Human-first commerce</h3><p class="muted">Clear pricing, informed consent, easy cancellation, portable data and no deceptive scarcity.</p></div><div class="feature"><div class="feature-icon">♧</div><h3>Gaia-aware operations</h3><p class="muted">Lightweight pages, caching, optimized media and measurable resource use. Impact claims stay evidence-based.</p></div><div class="feature"><div class="feature-icon">∞</div><h3>Durable value</h3><p class="muted">Revenue is built around useful commerce, memberships, merchant tools and transparent platform services—not promises of asset appreciation.</p></div></section><section class="section split"><div class="feature"><span class="tag">REVENUE ENGINE</span><h3>Multiple real revenue streams</h3><p class="muted">Merchant subscriptions • marketplace fees • premium memberships • promoted discovery • digital goods • service integrations • partner campaigns.</p></div><div class="feature"><span class="tag">USER CONTROL</span><h3>Return because it is useful</h3><p class="muted">Rewards, saved carts, subscriptions, personalization and referrals are optional tools that users can control.</p></div></section>','Gaia — Rollin')}
function home(){shell('<section class="hero"><div class="hero-card"><div class="eyebrow">ROLLIN COMMERCE OS</div><h1>SHOP.<br>EARN.<br>REPEAT.</h1><p>A premium marketplace built around real utility: products, subscriptions, rewards, drops, referrals and memberships.</p><div class="hero-actions"><button class="primary" onclick="location.hash=\'shop\'">Explore Shop →</button><button class="secondary" onclick="location.hash=\'rewards\'">View Rewards</button></div></div><div class="wallet-card"><div><div class="eyebrow">ROLLIN WALLET</div><div class="balance">— ROLLIN</div><div class="status"><span class="dot"></span> Network not configured</div></div><div><p class="muted">Your wallet stays protected from invented balances and fake confirmations.</p><button class="secondary" onclick="location.hash=\'wallet\'">Open Wallet</button></div></div></section><section class="section"><div class="stats"><div class="stat">Cart<strong>'+state.cart.length+'</strong></div><div class="stat">Orders<strong>'+state.orders.length+'</strong></div><div class="stat">Rewards<strong>'+state.rewards+'</strong></div><div class="stat">Tier<strong>'+state.tier+'</strong></div></div></section><section class="section"><div class="section-head"><h2>Trending now</h2><button class="secondary" onclick="location.hash=\'shop\'">View all</button></div><div class="grid">'+products.slice(0,4).map(productCard).join("")+'</div></section><section class="section"><div class="feature-grid"><div class="feature"><div class="feature-icon">↻</div><h3>Repeat purchase engine</h3><p class="muted">Subscriptions, streaks and member benefits create legitimate reasons to return.</p></div><div class="feature"><div class="feature-icon">↗</div><h3>Shareable by design</h3><p class="muted">Every product and drop has a share-ready route and referral architecture.</p></div><div class="feature"><div class="feature-icon">◇</div><h3>12-asset ecosystem</h3><p class="muted">Rollin leads while the other supplied assets remain configurable and transparent.</p></div></div></section>')}
function productCard(p){return '<article class="card"><div class="product-art">'+p.icon+'</div><div class="card-body"><span class="tag">'+p.tag+'</span><h3>'+p.name+'</h3><p class="muted">'+p.desc+'</p><div class="price">'+money(p.price)+' <small>· demo</small></div><div class="card-actions"><button class="primary" data-add="'+p.id+'">Add</button><button class="secondary" data-share="'+p.id+'">Share</button></div></div></article>'}
function shop(){shell('<div class="section-head"><div><div class="eyebrow">MARKETPLACE</div><h2>Discover your next buy</h2></div><button class="secondary" onclick="location.hash=\'cart\'">Cart ('+state.cart.length+')</button></div><div class="toolbar"><input id="search" class="search" placeholder="Search products, categories, merchants…"><button class="secondary" onclick="location.hash=\'drops\'">Live drops</button></div><div id="shopGrid" class="grid">'+products.map(productCard).join("")+'</div>');el("#search").oninput=e=>{const q=e.target.value.toLowerCase();el("#shopGrid").innerHTML=products.filter(p=>(p.name+p.cat+p.desc).toLowerCase().includes(q)).map(productCard).join("")}}
function drops(){const now=Date.now();const ends=now+36e5; shell('<div class="drop-banner"><div class="eyebrow">LIMITED DROP</div><h2>Emrld Member Drop</h2><p class="muted">Inventory and timing are application data — not manufactured scarcity.</p><strong id="countdown">36:00:00</strong></div><div class="grid">'+products.filter(p=>p.tag==="LIMITED"||p.cat==="Drops").map(productCard).join("")+'</div><section class="section"><div class="notice">Share this drop with your referral link: <strong>'+location.origin+location.pathname+'#drops?ref='+state.ref+'</strong></div></section>');const timer=setInterval(()=>{const left=Math.max(0,ends-Date.now());const h=Math.floor(left/36e5),m=Math.floor(left%36e5/6e4),s=Math.floor(left%6e4/1e3);const c=el("#countdown");if(c)c.textContent=[h,m,s].map(x=>String(x).padStart(2,"0")).join(":");else clearInterval(timer)},1000)}
function rewards(){shell('<div class="eyebrow">LOYALTY</div><h2>Rewards that bring you back</h2><p class="muted">Credits and benefits—not promises of token appreciation.</p><section class="section"><div class="stats"><div class="stat">Reward credits<strong>'+state.rewards+'</strong></div><div class="stat">Membership<strong>'+state.tier+'</strong></div><div class="stat">Streak<strong>0 days</strong></div><div class="stat">Referrals<strong>0</strong></div></div></section><section class="section split"><div class="feature"><span class="tag">ROLLIN PASS</span><h2>Member</h2><p class="muted">Early access, member pricing and enhanced platform rewards.</p><button class="primary" onclick="upgradeTier()">Choose Member</button></div><div class="feature"><span class="tag">REFERRAL</span><h2>Share & earn</h2><p class="muted">Your referral code is <strong>'+state.ref+'</strong>.</p><button class="secondary" onclick="navigator.clipboard?.writeText(location.origin+location.pathname+'?ref='+state.ref);toast("Referral link copied")">Copy link</button></div></div>')}
function wallet(){shell('<div class="eyebrow">WALLET</div><h2>Universal wallet</h2><p class="muted">Verified blockchain data only.</p><div class="notice" style="margin:20px 0"><strong>Network status:</strong> Not configured. The application will not display invented balances or confirmations.</div><div class="grid">'+TOKENS.map((t,i)=>'<div class="card"><div class="card-body"><span class="tag">'+(i===0?"PRIMARY":"ECOSYSTEM")+'</span><h3>'+t[0]+'</h3><p class="muted" style="word-break:break-all;font-size:.75rem">'+t[1]+'</p><strong>Balance unavailable</strong></div></div>').join("")+'</div>')}
function profile(){shell('<div class="eyebrow">PROFILE</div><h2>Your Rollin account</h2><div class="split section"><div class="feature"><h3>Referral identity</h3><p class="muted">'+state.ref+'</p><button class="secondary" onclick="navigator.clipboard?.writeText(state.ref);toast("Copied")">Copy</button></div><div class="feature"><h3>Theme</h3><p class="muted">Use the ◐ control to switch presentation mode.</p><button class="secondary" onclick="location.hash=\'legal\'">Trust & policies</button></div></div><section class="section"><h2>Orders</h2>'+ (state.orders.length?'<table class="table"><tr><th>Order</th><th>Total</th><th>Status</th></tr>'+state.orders.map(o=>'<tr><td>'+o.id+'</td><td>'+money(o.total)+'</td><td>DEMO / not blockchain-confirmed</td></tr>').join("")+'</table>':'<div class="empty">No orders yet. Start with the Shop.</div>')+'</section>')}
function cart(){const items=state.cart.map(id=>products.find(p=>p.id===id)).filter(Boolean);const total=items.reduce((a,p)=>a+p.price,0);shell('<div class="section-head"><div><div class="eyebrow">CART</div><h2>Your cart</h2></div><button class="secondary" onclick="location.hash=\'shop\'">Continue shopping</button></div>'+ (items.length?'<div class="grid">'+items.map(productCard).join("")+'</div><section class="section"><div class="feature"><h3>Demo total</h3><div class="balance">'+money(total)+'</div><p class="muted">Checkout is in demo mode until network/payment configuration is verified.</p><button class="primary" onclick="location.hash=\'checkout\'">Continue to checkout</button></div></section>':'<div class="empty">Your cart is empty.</div>'))}
function checkout(){const items=state.cart.map(id=>products.find(p=>p.id===id)).filter(Boolean),total=items.reduce((a,p)=>a+p.price,0);shell('<div class="eyebrow">CHECKOUT</div><h2>Universal checkout</h2><div class="split section"><div class="feature"><h3>Order summary</h3>'+items.map(p=>'<p>'+p.name+' <strong style="float:right">'+money(p.price)+'</strong></p>').join("")+'<hr><h3>Total <span style="float:right">'+money(total)+'</span></h3></div><div class="feature"><h3>Payment state</h3><div class="notice">Awaiting verified network configuration. No transaction will be submitted.</div><button class="primary" style="width:100%;margin-top:15px" onclick="createDemoOrder()">Create demo order</button></div></div>')}
function merchant(){shell('<div class="eyebrow">MERCHANT OS</div><h2>Sell with Rollin</h2><p class="muted">Storefront, products, drops, subscriptions, loyalty and analytics architecture.</p><div class="feature-grid section">'+["Storefront","Products & inventory","Subscriptions","Drops & campaigns","Customers","Settlement"].map(x=>'<div class="feature"><h3>'+x+'</h3><p class="muted">Ready for backend credentials and merchant approval.</p></div>').join("")+'</div>')}
function admin(){shell('<div class="eyebrow">ADMIN</div><h2>Operations console</h2><div class="stats section"><div class="stat">Products<strong>'+products.length+'</strong></div><div class="stat">Tokens<strong>12</strong></div><div class="stat">Treasury<strong>Configured</strong></div><div class="stat">Network<strong>Unset</strong></div></div><section class="section"><h3>Configured assets</h3><table class="table"><tr><th>Asset</th><th>Contract</th></tr>'+TOKENS.map(t=>'<tr><td>'+t[0]+'</td><td style="word-break:break-all">'+t[1]+'</td></tr>').join("")+'</table></section>')}
function legal(){shell('<div class="eyebrow">TRUST</div><h2>Policies</h2><div class="feature-grid section">'+["Terms","Privacy","Refund Policy","Merchant Terms","Risk Disclosure","Contact"].map(x=>'<div class="feature"><h3>'+x+'</h3><p class="muted">Production policy content should be reviewed and finalized before commercial launch.</p></div>').join("")+'</div>')}
function addToCart(id){state.cart.push(id);save();toast("Added to cart");render()}
function buyNow(id){state.cart.push(id);save();location.hash="checkout"}
function createDemoOrder(){const items=state.cart.map(id=>products.find(p=>p.id===id)).filter(Boolean),total=items.reduce((a,p)=>a+p.price,0);state.orders.push({id:"DEMO-"+Date.now().toString(36).toUpperCase(),total});state.rewards+=Math.max(1,Math.floor(total/10));state.cart=[];save();toast("Demo order created");setTimeout(()=>location.hash="profile",500)}
function upgradeTier(){state.tier="Member";save();toast("Member tier selected")}
function shareProduct(id){const p=products.find(x=>x.id===id);const url=location.origin+location.pathname+"#shop?product="+id+"&ref="+state.ref;if(navigator.share)navigator.share({title:p.name,text:"Discover this on Rollin",url}).catch(()=>{});else navigator.clipboard?.writeText(url);toast("Share link ready")}
function openModal(html){el("#modal").innerHTML='<div class="modal-box">'+html+'</div>';el("#modal").classList.remove("hidden")}function closeModal(){el("#modal").classList.add("hidden")}window.closeModal=closeModal;function toast(s){const t=el("#toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}window.addToCart=addToCart;window.upgradeTier=upgradeTier;window.createDemoOrder=createDemoOrder;window.shareProduct=shareProduct;window.toast=toast;
render();