import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const S=createClient("https://qwjjaxzmneawwppcpaap.supabase.co","sb_publishable_X1eIeVVNUOHuhmL_10bkDw_1HuT4Vcq");
const B=new URL("./",import.meta.url).pathname;
const C={real_estate:["Real Estate","⌂"],vehicle:["Cars + Trucks","▣"],boat:["Boats","◒"],aircraft:["Planes","✈"]};
let listings=[],session=null;
const $=s=>document.querySelector(s), esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])), money=c=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(c||0)/100);
function go(p,q=""){location.href=p==="home"?B:B+p.replace(/^\/+|\/+$/g,"")+"/"+(q?"?"+q:"")}
async function load(){const r=await S.auth.getSession();session=r.data.session;const x=await S.from("rollin_listings").select("*").in("status",["active","under_offer"]).order("created_at",{ascending:false});listings=x.data||[]}
function card(x){return '<article class="card"><div class="product-art"><span>'+C[x.category][1]+'</span></div><div class="card-body"><span class="tag">'+C[x.category][0]+'</span><h3>'+esc(x.title)+'</h3><p class="muted">'+esc(x.location_text||"Location disclosed by owner")+'</p><div class="price">'+money(x.price_cents)+'</div><p class="muted">'+esc(x.description||"")+'</p><div class="card-actions"><a class="primary" href="'+B+'listing/?id='+x.id+'">View listing →</a><span class="tag">'+(x.crypto_enabled?"CRYPTO READY":"DIRECT SALE")+'</span></div></div></article>'}
function shell(h){document.title="Rollin — Owner-First Asset Marketplace";$("#view").innerHTML='<div class="page">'+h+'</div>'}
function marketplace(cat){const q=new URLSearchParams(location.search).get("q")||"";const z=listings.filter(x=>(!cat||x.category===cat)&&(!q||(x.title+" "+x.description+" "+(x.location_text||"")).toLowerCase().includes(q.toLowerCase())));shell('<div class="section-head"><div><div class="eyebrow">ROLLIN FSBO</div><h2>'+(cat?C[cat][0]:"Owner Marketplace")+'</h2><p class="muted">For Sale By Owner — real estate, cars + trucks, boats and planes only.</p></div><a class="primary" href="'+B+'list/">List an asset →</a></div><div class="toolbar"><input id="q" class="search" value="'+esc(q)+'" placeholder="Search owner listings…"></div><div class="grid">'+(z.length?z.map(card).join(""):'<div class="empty wide">No matching owner listings yet.</div>')+'</div>');$("#q").oninput=e=>{const u=new URL(location.href);e.target.value?u.searchParams.set("q",e.target.value):u.searchParams.delete("q");history.replaceState({}, "", u);marketplace(cat)}}
async function detail(){const id=Number(new URLSearchParams(location.search).get("id")),x=listings.find(v=>Number(v.id)===id);if(!x){shell('<section class="section feature"><h2>Listing not found</h2><a class="primary" href="'+B+'shop/">Browse listings</a></section>');return}shell('<div class="section-head"><div><div class="eyebrow">FOR SALE BY OWNER</div><h2>'+esc(x.title)+'</h2><p class="muted">'+C[x.category][0]+' · '+esc(x.location_text||"Location disclosed by owner")+'</p></div><a class="secondary" href="'+B+'shop/">Back to marketplace</a></div><section class="section split"><div class="feature"><span class="tag">'+(x.crypto_enabled?"CRYPTO SALE CAPABLE":"DIRECT SALE")+'</span><div class="price">'+money(x.price_cents)+'</div><p class="muted">'+esc(x.description)+'</p></div><div class="feature"><h3>Owner transaction</h3><p class="muted">Buyer and owner can arrange inspection, title/document review, closing and transfer through the appropriate process for the asset.</p><a class="primary full" href="mailto:?subject=Rollin FSBO inquiry: '+encodeURIComponent(x.title)+'">Contact owner →</a><div class="section"><h3>Crypto offer</h3><p class="muted">Non-custodial Base USDC offer workflow. Rollin does not hold buyer funds.</p><input id="offerAmount" class="search full" type="number" min="1" step=".01" placeholder="Offer amount (USD equivalent)"><textarea id="offerMessage" class="search full" placeholder="Offer terms / inspection / closing notes"></textarea><button id="offerBtn" class="secondary full">Submit USDC offer →</button></div></div></section>')}
async function bindOffer(x){const b=$("#offerBtn");if(!b)return;b.onclick=async()=>{if(!session)return go("profile");const amount=Number($("#offerAmount").value);if(!amount)return alert("Enter an offer amount.");const r=await S.from("rollin_listing_offers").insert({listing_id:x.id,buyer_id:session.user.id,seller_id:x.seller_id,amount_cents:Math.round(amount*100),asset:"USDC",network:"base",message:$("#offerMessage").value.trim()});if(r.error)return alert(r.error.message);alert("Crypto offer submitted");};}
async function list(){if(!session){shell('<section class="section feature"><h2>List directly as the owner</h2><p class="muted">Sign in to publish a real estate, car/truck, boat or plane.</p><a class="primary" href="'+B+'profile/">Sign in / create account →</a></section>');return}shell('<div class="eyebrow">ROLLIN FSBO</div><h2>List your asset</h2><p class="muted">Owner-only categories. Crypto sale capability is built into the listing workflow.</p><section class="section feature"><select id="cat" class="search full"><option value="real_estate">Real Estate</option><option value="vehicle">Cars + Trucks</option><option value="boat">Boats</option><option value="aircraft">Planes</option></select><input id="title" class="search full" placeholder="Listing title"><input id="price" class="search full" type="number" min="0" step=".01" placeholder="Asking price (USD)"><input id="loc" class="search full" placeholder="City / State or general location"><textarea id="desc" class="search full" placeholder="Description, condition, history, terms"></textarea><label class="muted"><input id="crypto" type="checkbox" checked> Crypto sale capable — Base USDC</label><button id="publish" class="primary full">Publish owner listing →</button></section>');$("#publish").onclick=async()=>{const title=$("#title").value.trim(),price=Number($("#price").value);if(!title||price<0)return alert("Add a title and valid asking price.");const r=await S.from("rollin_listings").insert({seller_id:session.user.id,category:$("#cat").value,title,price_cents:Math.round(price*100),location_text:$("#loc").value.trim(),description:$("#desc").value.trim(),crypto_enabled:$("#crypto").checked});if(r.error)return alert(r.error.message);go("shop")}}
async function render(){await load();const p=location.pathname.slice(B.length).split("/").filter(Boolean)[0]||"home";if(p==="listing"){await detail();const id=Number(new URLSearchParams(location.search).get("id"));const x=listings.find(v=>Number(v.id)===id);if(x)await bindOffer(x);return;}if(p==="list")return list();if(p==="real-estate")return marketplace("real_estate");if(p==="cars-trucks")return marketplace("vehicle");if(p==="boats")return marketplace("boat");if(p==="planes")return marketplace("aircraft");marketplace(null)}
render();